{
    "repository": "xyproto/algernon",
    "clone_url": "https://github.com/xyproto/algernon.git",
    "timestamp": "2023-05-30T11:06:25.116754Z",
    "clone_success": true,
    "number of actions": 3,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Build/test-cache] \ud83d\ude80  Start image=crawlergpt:latest\n[Build/test      ] \ud83d\ude80  Start image=crawlergpt:latest\n[Build/test-cache]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Build/test-cache]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Build/test      ]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Build/test-cache]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Build/test-cache]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/c66e4e10-fed3-11ed-a890-af2cc187fc11/xyproto-algernon] user=0 workdir=\n[Build/test-cache]   \u2601  git clone 'https://github.com/actions/setup-go' # ref=v2\n[Build/test-cache] Unable to reset to bfdd3570ce990073878bf10f6b2d79082de49492: EOF\n[Build/test-cache] \ud83c\udfc1  Job succeeded\n",
    "actions_stderr": "Error: Error response from daemon: remove act-Build-test-33fb9eca85a563d2541f22c1e64a087bf70b33bb021ca61b88cf7c78f842cd71-env: volume is in use - [c7ffd52d925743972fa4f4b8c612cdd38b870e3cbd01c2c462818a0f22d69524]\n"
}