{
    "repository": "gin-contrib/secure",
    "clone_url": "https://github.com/gin-contrib/secure.git",
    "timestamp": "2023-05-30T11:23:42.959903Z",
    "clone_success": true,
    "number of actions": 3,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Run Tests/ubuntu-latest @ Go 1.14] \ud83d\ude80  Start image=crawlergpt:latest\n[Run Tests/lint                   ] \ud83d\ude80  Start image=crawlergpt:latest\n[Run Tests/lint                   ]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Run Tests/ubuntu-latest @ Go 1.14]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Run Tests/lint                   ]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Run Tests/ubuntu-latest @ Go 1.14]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n",
    "actions_stderr": "Error: failed to create container: 'Error response from daemon: Conflict. The container name \"/act-Run-Tests-lint-2a484cb91100205092bf0ed3dc5f4a66e9b46c6afaf6d423fd5800e1a53dce50\" is already in use by container \"97fadcefe7e0525b5168efbdea367c2f5387c781ea662b1e6f3406b35b2e9066\". You have to remove (or rename) that container to be able to reuse that name.'\n"
}