{
    "repository": "MangaManagerORG/Manga-Manager",
    "stars": 86,
    "language": "python",
    "size": 53269,
    "clone_url": "https://github.com/MangaManagerORG/Manga-Manager.git",
    "timestamp": "2023-07-01T17:14:20.856327Z",
    "clone_success": true,
    "number_of_actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_build_tools": [
        "unittest"
    ],
    "actions_test_build_tools": [
        "unittest"
    ],
    "actions_run": {
        "failed": true,
        "tests": [],
        "stdout": "[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ] \ud83d\ude80  Start image=crawlergpt:latest\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ] \ud83d\ude80  Start image=crawlergpt:latest\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \ud83d\ude80  Start image=crawlergpt:latest\n[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager] user=0 workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager] user=0 workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager] user=0 workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ] \u2b50 Run Main actions/checkout@v3\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ] \u2b50 Run Main Checkout code\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \u2705  Success - Main Checkout code\n[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ]   \u2705  Success - Main actions/checkout@v3\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ] \u2b50 Run Main Set latest release commit hash (latest)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/release_commit] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/SonarCloud         ] \ud83c\udfc1  Job succeeded\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \u2705  Success - Main Set latest release commit hash (latest)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \u2699  ::set-output:: release_commit=0fc5a24\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ] \u2b50 Run Main Set latest commit hash (develop)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/latest_commit] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \u2705  Success - Main Set latest commit hash (develop)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ]   \u2699  ::set-output:: latest_commit=698a275\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Parse Versions Env ] \ud83c\udfc1  Job succeeded\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \ud83e\uddea  Matrix: map[python-version:3.11]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \u2b50 Run Main actions/checkout@v3\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2705  Success - Main actions/checkout@v3\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \u2b50 Run Main actions/setup-python@v4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker cp src=/tmp/act-cache/92ad3bf6-7396-4142-9e4b-1c6e27773fd8/act/actions-setup-python@v4/ dst=/var/run/act/actions/actions-setup-python@v4/\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/actions-setup-python@v4/] user=0 workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v4/dist/setup/index.js] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Python is expected to be installed into /opt/hostedtoolcache\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2753  ::group::Installed versions\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Semantic version spec of 3.11 is 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? false\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::evaluating 6 versions\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::match not found\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Version 3.11 was not found in the local cache\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Getting manifest from actions/python-versions@main\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::set auth\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-beta.3 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-beta.2 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-beta.1 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-alpha.7 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-alpha.6 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-alpha.5 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-alpha.4 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-alpha.3 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-alpha.2 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.12.0-alpha.1 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::check 3.11.4 satisfies 3.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::arm64===x64 && darwin===linux\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::x64===x64 && darwin===linux\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::x64===x64 && linux===linux\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::matched 3.11.4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Version 3.11 is available for downloading\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Download from \"https://github.com/actions/python-versions/releases/download/3.11.4-5199054971/python-3.11.4-linux-20.04-x64.tar.gz\"\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Downloading https://github.com/actions/python-versions/releases/download/3.11.4-5199054971/python-3.11.4-linux-20.04-x64.tar.gz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Destination /tmp/4f7b4e7e-43aa-4171-ae27-be0c76fd04d6\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::set auth\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::download complete\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Extract downloaded archive\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Checking tar --version\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::tar (GNU tar) 1.30%0ACopyright (C) 2017 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | [command]/usr/bin/tar xz --warning=no-unknown-keyword -C /tmp/9dd34124-4f3a-4861-832a-056fd21a21cc -f /tmp/4f7b4e7e-43aa-4171-ae27-be0c76fd04d6\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Execute installation script\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Check if Python hostedtoolcache folder exist...\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Create Python 3.11.4 folder\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Copy Python binaries to hostedtoolcache folder\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Upgrading pip...\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Looking in links: /tmp/tmp7hfda7fa\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages (65.5.0)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages (23.1.2)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting pip\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 2.1/2.1 MB 15.1 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Installing collected packages: pip\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Successfully installed pip-23.1.2\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Create complete file\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? false\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.11.4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::explicit? true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::evaluating 7 versions\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::matched: 3.11.4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.11.4/x64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Found tool in cache Python 3.11.4 x64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Successfully set up CPython (3.11.4)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2753  ::endgroup::\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::followSymbolicLinks 'true'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::followSymbolicLinks 'true'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::implicitDescendants 'true'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::matchDirectories 'true'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::omitBrokenSymbolicLinks 'true'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Search path '/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/requirements.txt\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Found 1 files to hash.\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::OS Name: Ubuntu, Version: 20.04\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | [command]/opt/hostedtoolcache/Python/3.11.4/x64/bin/pip cache dir\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | /home/runneradmin/.cache/pip\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::global cache directory path is /home/runneradmin/.cache/pip\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Resolved Keys:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::[\"setup-python-Linux-20.04-Ubuntu-python-3.11.4-pip-ee9194a7126a472f52ad4f39558c49e1925edad08cd21a0862ec4134362a89b5\",\"setup-python-Linux-20.04-Ubuntu-python-3.11.4-pip\"]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Checking zstd --quiet --version\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::1.5.0\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::zstd version: 1.5.0\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Resource Url: http://130.242.72.40:40823/_apis/artifactcache/cache?keys=setup-python-Linux-20.04-Ubuntu-python-3.11.4-pip-ee9194a7126a472f52ad4f39558c49e1925edad08cd21a0862ec4134362a89b5%252Csetup-python-Linux-20.04-Ubuntu-python-3.11.4-pip&version=79a244514713d0ea96d5d8aab70186082a897848df6e845ec8308965d2f82f4f\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Failed to delete archive: Error: ENOENT: no such file or directory, unlink ''\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | pip cache is not found\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2753 add-matcher /run/act/actions/actions-setup-python@v4/.github/python.json\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2705  Success - Main actions/setup-python@v4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.11.4/x64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-env:: PKG_CONFIG_PATH=/opt/hostedtoolcache/Python/3.11.4/x64/lib/pkgconfig\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-env:: Python_ROOT_DIR=/opt/hostedtoolcache/Python/3.11.4/x64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-env:: Python2_ROOT_DIR=/opt/hostedtoolcache/Python/3.11.4/x64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-env:: Python3_ROOT_DIR=/opt/hostedtoolcache/Python/3.11.4/x64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.11.4/x64/lib\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-output:: python-version=3.11.4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-output:: python-path=/opt/hostedtoolcache/Python/3.11.4/x64/bin/python\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::set-output:: cache-hit=false\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.11.4/x64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.11.4/x64/bin\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \u2b50 Run Main sudo apt install xvfb\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | WARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Reading package lists...\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Building dependency tree...\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Reading state information...\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | xvfb is already the newest version (2:1.20.11-1ubuntu1~20.04.2).\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2705  Success - Main sudo apt install xvfb\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \u2b50 Run Main pip install -r requirements.txt\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting prompt_toolkit>=3.0.31 (from -r requirements.txt (line 1))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading prompt_toolkit-3.0.38-py3-none-any.whl (385 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 385.8/385.8 kB 6.1 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting pillow>=9.4.0 (from -r requirements.txt (line 2))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading Pillow-10.0.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 3.4/3.4 MB 24.4 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting natsort>=8.2.0 (from -r requirements.txt (line 4))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading natsort-8.4.0-py3-none-any.whl (38 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting lxml>=4.9.1 (from -r requirements.txt (line 5))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading lxml-4.9.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.2 MB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 7.2/7.2 MB 21.0 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting six>=1.16.0 (from -r requirements.txt (line 6))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting requests~=2.28.2 (from -r requirements.txt (line 7))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading requests-2.28.2-py3-none-any.whl (62 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 62.8/62.8 kB 641.3 kB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting anytree~=2.8.0 (from -r requirements.txt (line 8))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading anytree-2.8.0-py2.py3-none-any.whl (41 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 41.7/41.7 kB 1.5 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting numpy~=1.24.2 (from -r requirements.txt (line 9))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 17.3/17.3 MB 33.0 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting rarfile (from -r requirements.txt (line 10))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading rarfile-4.0-py3-none-any.whl (28 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting wcwidth (from prompt_toolkit>=3.0.31->-r requirements.txt (line 1))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting charset-normalizer<4,>=2 (from requests~=2.28.2->-r requirements.txt (line 7))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (197 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 197.3/197.3 kB 8.5 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting idna<4,>=2.5 (from requests~=2.28.2->-r requirements.txt (line 7))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading idna-3.4-py3-none-any.whl (61 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 61.5/61.5 kB 491.8 kB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting urllib3<1.27,>=1.21.1 (from requests~=2.28.2->-r requirements.txt (line 7))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading urllib3-1.26.16-py2.py3-none-any.whl (143 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 143.1/143.1 kB 10.8 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting certifi>=2017.4.17 (from requests~=2.28.2->-r requirements.txt (line 7))\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 157.0/157.0 kB 3.2 MB/s eta 0:00:00\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Installing collected packages: wcwidth, rarfile, urllib3, six, prompt_toolkit, pillow, numpy, natsort, lxml, idna, charset-normalizer, certifi, requests, anytree\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Successfully installed anytree-2.8.0 certifi-2023.5.7 charset-normalizer-3.1.0 idna-3.4 lxml-4.9.2 natsort-8.4.0 numpy-1.24.4 pillow-10.0.0 prompt_toolkit-3.0.38 rarfile-4.0 requests-2.28.2 six-1.16.0 urllib3-1.26.16 wcwidth-0.2.6\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2705  Success - Main pip install -r requirements.txt\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \u2b50 Run Main Start xvfb\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2705  Success - Main Start xvfb\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \u2b50 Run Main Run the tests\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Collecting unittest-xml-reporting\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   Downloading unittest_xml_reporting-3.2.0-py2.py3-none-any.whl (20 kB)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Requirement already satisfied: lxml in /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages (from unittest-xml-reporting) (4.9.2)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Installing collected packages: unittest-xml-reporting\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Successfully installed unittest-xml-reporting-3.2.0\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | sub_mm_path:/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Running tests...\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | ----------------------------------------------------------------------\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Found extensions: ['/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/Extensions/CoverDownloader/CoverDownloader.py', '/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/Extensions/WebpConverter/WebpConverter.py']\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | MetadataSources module loaded\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/src/Layouts\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Found modules: []\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Found extensions: []\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/src/Layouts\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Found modules: []\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Found extensions: []\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | ...Assert series name matches\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Assert loc series name matches\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Assert series name matches\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Apending cover to efectively delete it. Loading 'Test__new_cover.jpeg'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding file '~9999_Back.jpeg' to new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Apending cover to efectively delete it. Loading 'Test__new_cover.jpeg'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding file '~9999_Back.jpeg' to new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Super setup\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_Generated1449.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_Generated3243.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__new_cover.jpeg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Apending cover to efectively delete it. Loading 'Test__new_cover.jpeg'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding file '!0000_Cover.jpeg' to new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Apending cover to efectively delete it. Loading 'Test__new_cover.jpeg'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding file '!0000_Cover.jpeg' to new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super setup\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_Generated2761.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_Generated5168.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__new_cover.jpeg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Skipping back cover to efectively delete it. File: '003.png'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Skipping back cover to efectively delete it. File: '003.png'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super setup\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image less\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image less\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_Generated5317.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_Generated3521.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__new_cover.jpeg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .TRACE:LoadedCInfo:[Recompressing] Skipping cover to effectively delete it. File: '000.png'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Skipping cover to effectively delete it. File: '000.png'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super setup\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image less\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image less\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_Generated3566.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_Generated4012.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__new_cover.jpeg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super setup\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_Generated1416.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_Generated1255.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__new_cover.jpeg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Exception ignored in: <function PhotoImage.__del__ at 0x7f9585b249a0>\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/PIL/ImageTk.py\", line 131, in __del__\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     name = self.__photo.name\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |            ^^^^^^^^^^^^\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '000.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '001.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '002.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding '003.png' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super setup\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting the processed file has one image more\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Super Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_Generated2961.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_Generated246.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__new_cover.jpeg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Running unit tests for cover filename parsing\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Selected file is: 000001.jpg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Selected file is: cover_0001.jpg\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile1.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile2.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile3.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile4.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile1.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile2.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile3.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile4.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile1.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile2.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile3.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile4.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |  test_simple_backup\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Setup:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__0_81.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__1_3917.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__2_1906.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting backup is in the file\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Making sure the backed up file has content and matches original values:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting backup is in the file\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Making sure the backed up file has content and matches original values:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting backup is in the file\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Making sure the backed up file has content and matches original values:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_81.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_3917.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__2_1906.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__nometadata.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile1.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile2.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile3.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile4.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |  test_simple_backup_nometadata\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Setup:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__0_1697.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__1_5417.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__2_5992.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Asserting backup is in the file\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_1697.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_5417.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__2_5992.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__nometadata.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | ./tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |  test_simple_read\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Setup:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__0_731.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__1_3494.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__2_4847.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_731.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_3494.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__2_4847.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__nometadata.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile1.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile2.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile3.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile4.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile1.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile2.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile3.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile4.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile1.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile2.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile3.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:LoadedCInfo:[Recompressing] Adding 'Dummyfile4.ext' back to the new tempfile\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |  test_simple_write\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Setup:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__0_2816.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__1_5709.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: Test__2_3081.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Writing new values\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Test files keep all images\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Testing reading saved values\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__0_2816.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__1_5709.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__2_3081.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: Test__nometadata.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .ERROR:LoadedCInfo:Could not get ['key_here'] keys when filling template values\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .TRACE:MetaManager.Core:[Merging] Ignoring Title. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Series. Keeping old values\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring LocalizedSeries. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Number. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Count. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Volume. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AlternateSeries. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AlternateNumber. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AlternateCount. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Summary. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Notes. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Year. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Month. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Day. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Penciller. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Inker. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Colorist. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Letterer. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring CoverArtist. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Editor. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Translator. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Publisher. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Imprint. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Genre. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Tags. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Web. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring LanguageISO. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Format. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring BlackAndWhite. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Manga. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Characters. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Teams. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Locations. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring ScanInformation. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring StoryArc. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring StoryArcNumber. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring SeriesGroup. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AgeRating. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring CommunityRating. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring MainCharacterOrTeam. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Other. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Review. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring GTIN. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Title. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Series. Keeping old values\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring LocalizedSeries. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Number. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Count. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Volume. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AlternateSeries. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AlternateNumber. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AlternateCount. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Summary. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Notes. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Year. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Month. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Day. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Penciller. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Inker. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Colorist. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Letterer. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring CoverArtist. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Editor. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Translator. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Publisher. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Imprint. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Genre. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Tags. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Web. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring LanguageISO. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Format. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring BlackAndWhite. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Manga. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Characters. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Teams. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Locations. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring ScanInformation. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring StoryArc. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring StoryArcNumber. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring SeriesGroup. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring AgeRating. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring CommunityRating. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring MainCharacterOrTeam. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Other. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring Review. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | TRACE:MetaManager.Core:[Merging] Ignoring GTIN. Field has not changed\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Creating: random_image_1_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Assert values are kept\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Assert values are overwritten\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_1_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_1_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | [Errno 2] No such file or directory: 'random_image_1_not_image.ext.cbz'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_0_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_1_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_0_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_1_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .ssERROR:MetaManager.Core:Failed to write changes because of missing permissions or because other program has the file opened\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/src/MetadataManager/MetadataManagerLib.py\", line 114, in process\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     loaded_cinfo.write_metadata()\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/tests/MetadataManagerTests/test_MetadataEditorCore.py\", line 182, in write_metadata\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     raise PermissionError(\"This exception is raised as part of one unit test. Safe to ignore\")\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | PermissionError: This exception is raised as part of one unit test. Safe to ignore\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | ERROR:MetaManager.Core:Failed to write changes because of missing permissions or because other program has the file opened\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/src/MetadataManager/MetadataManagerLib.py\", line 114, in process\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     loaded_cinfo.write_metadata()\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/tests/MetadataManagerTests/test_MetadataEditorCore.py\", line 182, in write_metadata\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     raise PermissionError(\"This exception is raised as part of one unit test. Safe to ignore\")\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | PermissionError: This exception is raised as part of one unit test. Safe to ignore\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_0_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_1_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .ERROR:MetaManager.Core:Unhandled exception saving changes\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/src/MetadataManager/MetadataManagerLib.py\", line 114, in process\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     loaded_cinfo.write_metadata()\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/tests/MetadataManagerTests/test_MetadataEditorCore.py\", line 206, in write_metadata\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     raise Exception(\"Exception. This exception is raised as part of one unit test. Safe to ignore\")\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Exception: Exception. This exception is raised as part of one unit test. Safe to ignore\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | ERROR:MetaManager.Core:Unhandled exception saving changes\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Traceback (most recent call last):\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/src/MetadataManager/MetadataManagerLib.py\", line 114, in process\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     loaded_cinfo.write_metadata()\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |   File \"/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/MangaManager/tests/MetadataManagerTests/test_MetadataEditorCore.py\", line 206, in write_metadata\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |     raise Exception(\"Exception. This exception is raised as part of one unit test. Safe to ignore\")\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Exception: Exception. This exception is raised as part of one unit test. Safe to ignore\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Teardown:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_0_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   |      Deleting: random_image_1_not_image.ext.cbz\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Cleaning up created settings.ini\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Cleaning up created settings.ini\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | .Cleaning up created settings.ini\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | ..\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | ----------------------------------------------------------------------\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Ran 28 tests in 1.074s\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | OK (skipped=2)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | \n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Generating XML reports...\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2705  Success - Main Run the tests\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \u2b50 Run Post actions/setup-python@v4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v4/dist/cache-save/index.js] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::paths for caching are /home/runneradmin/.cache/pip\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Checking zstd --quiet --version\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::1.5.0\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::zstd version: 1.5.0\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::implicitDescendants 'false'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::followSymbolicLinks 'true'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::implicitDescendants 'false'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::omitBrokenSymbolicLinks 'true'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Search path '/home/runneradmin/.cache/pip'\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Matched: ../../../home/runneradmin/.cache/pip\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Cache Paths:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::[\"../../../home/runneradmin/.cache/pip\"]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Archive Path: /tmp/01255716-d4be-4f25-8e66-d03e93aa0b06/cache.tzst\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | [command]/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager --files-from manifest.txt --use-compress-program zstdmt\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::File Size: 31768433\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Reserving Cache\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Resource Url: http://130.242.72.40:40823/_apis/artifactcache/caches\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Saving Cache (ID: 1)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Upload cache\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Resource Url: http://130.242.72.40:40823/_apis/artifactcache/caches/1\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Upload concurrency: 4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Upload chunk size: 33554432\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Awaiting all uploads\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Uploading chunk of size 31768433 bytes at offset 0 with content range: bytes 0-31768432/*\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Commiting cache\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Cache Size: ~30 MB (31768433 B)\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \ud83d\udcac  ::debug::Resource Url: http://130.242.72.40:40823/_apis/artifactcache/caches/1\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Cache saved successfully\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   | Cache saved with the key: setup-python-Linux-20.04-Ubuntu-python-3.11.4-pip-ee9194a7126a472f52ad4f39558c49e1925edad08cd21a0862ec4134362a89b5\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux]   \u2705  Success - Post actions/setup-python@v4\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Python 3.11 - Linux] \ud83c\udfc1  Job succeeded\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ] \ud83d\ude80  Start image=crawlergpt:latest\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager] user=0 workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u2601  git clone 'https://github.com/docker/setup-qemu-action' # ref=v2\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u2601  git clone 'https://github.com/docker/setup-buildx-action' # ref=v2\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u2601  git clone 'https://github.com/docker/login-action' # ref=v2\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u2601  git clone 'https://github.com/docker/build-push-action' # ref=v3\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ] \u2b50 Run Main Set up QEMU\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udc33  docker cp src=/tmp/act-cache/92ad3bf6-7396-4142-9e4b-1c6e27773fd8/act/docker-setup-qemu-action@v2/ dst=/var/run/act/actions/docker-setup-qemu-action@v2/\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1013 /var/run/act/actions/docker-setup-qemu-action@v2/] user=0 workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/docker-setup-qemu-action@v2/dist/index.js] user= workdir=\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u2753  ::group::Docker info\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \ud83d\udcac  ::debug::Exec.exec: docker version\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   | [command]/usr/bin/docker version\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   | Client:\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  Version:           20.10.8+azure\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  API version:       1.41\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  Go version:        go1.16.7\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  Git commit:        3967b7d28e15a020e4ee344283128ead633b3e0c\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  Built:             Thu Jul 29 13:55:47 2021\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  OS/Arch:           linux/amd64\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  Context:           default\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   |  Experimental:      true\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   | Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version\": dial unix /var/run/docker.sock: connect: permission denied\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u2753  ::endgroup::\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u2757  ::error::The process '/usr/bin/docker' failed with exit code 1\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ]   \u274c  Failure - Main Set up QEMU\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ] exitcode '1': failure\n[9dadd91d-82da-44f2-9d03-416cb630cd11/Stable Build                    ] \ud83c\udfc1  Job failed\n",
        "stderr": "Error: Job 'Stable Build' failed\n",
        "workflow": {
            "path": "/tmp/558156d8-17ed-11ee-8a50-bb14de238602/MangaManagerORG-Manga-Manager/.github/workflows/Run_Tests-crawler.yml",
            "type": "unittest"
        },
        "workflow_name": "9dadd91d-82da-44f2-9d03-416cb630cd11",
        "build_tool": "unittest",
        "elapsed_time": 506.47540760040283
    }
}