{
    "repository": "ambitioninc/django-entity",
    "clone_url": "https://github.com/ambitioninc/django-entity.git",
    "timestamp": "2023-05-29T15:19:11.114963Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[entity tests/tests] \ud83d\ude80  Start image=crawlergpt:latest\n[entity tests/tests]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[entity tests/tests]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[entity tests/tests]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[entity tests/tests]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/ambitioninc-django-entity] user=0 workdir=\n[entity tests/tests]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[entity tests/tests] \ud83e\uddea  Matrix: map[django:Django~=2.2.0 experimental:false python:3.7]\n[entity tests/tests] \u2b50 Run Main actions/checkout@v2\n[entity tests/tests]   \u2705  Success - Main actions/checkout@v2\n[entity tests/tests] \u2b50 Run Main actions/setup-python@v2\n[entity tests/tests]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[entity tests/tests]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v2/] user=0 workdir=\n[entity tests/tests]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/setup/index.js] user= workdir=\n[entity tests/tests]   \ud83d\udcac  ::debug::Semantic version spec of 3.7 is 3.7\n[entity tests/tests]   \ud83d\udcac  ::debug::isExplicit: \n[entity tests/tests]   \ud83d\udcac  ::debug::explicit? false\n[entity tests/tests]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[entity tests/tests]   \ud83d\udcac  ::debug::explicit? true\n[entity tests/tests]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[entity tests/tests]   \ud83d\udcac  ::debug::explicit? true\n[entity tests/tests]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[entity tests/tests]   \ud83d\udcac  ::debug::explicit? true\n[entity tests/tests]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[entity tests/tests]   \ud83d\udcac  ::debug::explicit? true\n[entity tests/tests]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[entity tests/tests]   \ud83d\udcac  ::debug::explicit? true\n[entity tests/tests]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[entity tests/tests]   \ud83d\udcac  ::debug::explicit? true\n[entity tests/tests]   \ud83d\udcac  ::debug::evaluating 6 versions\n[entity tests/tests]   \ud83d\udcac  ::debug::matched: 3.7.11\n[entity tests/tests]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.7.11/x64\n[entity tests/tests]   \ud83d\udcac  ::debug::Found tool in cache Python 3.7.11 x64\n[entity tests/tests]   | Successfully setup CPython (3.7.11)\n[entity tests/tests]   \u2753 add-matcher /run/act/actions/actions-setup-python@v2/.github/python.json\n[entity tests/tests]   \u2705  Success - Main actions/setup-python@v2\n[entity tests/tests]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.7.11/x64\n[entity tests/tests]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.7.11/x64/lib\n[entity tests/tests]   \u2699  ::set-output:: python-version=3.7.11\n[entity tests/tests]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64\n[entity tests/tests]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64/bin\n[entity tests/tests] \u2b50 Run Main Setup\n[entity tests/tests]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[entity tests/tests]   | Python 3.7.11\n[entity tests/tests]   | Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (21.2.4)\n[entity tests/tests]   | Collecting pip\n[entity tests/tests]   |   Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)\n[entity tests/tests]   | Collecting wheel\n[entity tests/tests]   |   Downloading wheel-0.40.0-py3-none-any.whl (64 kB)\n[entity tests/tests]   | Installing collected packages: wheel, pip\n[entity tests/tests]   |   Attempting uninstall: pip\n[entity tests/tests]   |     Found existing installation: pip 21.2.4\n[entity tests/tests]   |     Uninstalling pip-21.2.4:\n[entity tests/tests]   |       Successfully uninstalled pip-21.2.4\n[entity tests/tests]   | Successfully installed pip-23.1.2 wheel-0.40.0\n[entity tests/tests]   | Collecting Django>=2.2 (from -r requirements/requirements.txt (line 1))\n[entity tests/tests]   |   Downloading Django-3.2.19-py3-none-any.whl (7.9 MB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 7.9/7.9 MB 33.4 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting django-activatable-model>=2.0.0 (from -r requirements/requirements.txt (line 2))\n[entity tests/tests]   |   Downloading django_activatable_model-3.0.1-py2.py3-none-any.whl (13 kB)\n[entity tests/tests]   | Collecting django-manager-utils>=2.0.0 (from -r requirements/requirements.txt (line 3))\n[entity tests/tests]   |   Downloading django_manager_utils-3.0.1-py2.py3-none-any.whl (21 kB)\n[entity tests/tests]   | Collecting jsonfield>=0.9.20 (from -r requirements/requirements.txt (line 4))\n[entity tests/tests]   |   Downloading jsonfield-3.1.0-py3-none-any.whl (8.0 kB)\n[entity tests/tests]   | Collecting python3-utils>=0.3 (from -r requirements/requirements.txt (line 5))\n[entity tests/tests]   |   Downloading python3_utils-0.4.0-py2.py3-none-any.whl (5.7 kB)\n[entity tests/tests]   | Collecting wrapt>=1.10.5 (from -r requirements/requirements.txt (line 6))\n[entity tests/tests]   |   Downloading wrapt-1.15.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (75 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 75.7/75.7 kB 14.1 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting asgiref<4,>=3.3.2 (from Django>=2.2->-r requirements/requirements.txt (line 1))\n[entity tests/tests]   |   Downloading asgiref-3.7.2-py3-none-any.whl (24 kB)\n[entity tests/tests]   | Collecting pytz (from Django>=2.2->-r requirements/requirements.txt (line 1))\n[entity tests/tests]   |   Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 502.3/502.3 kB 11.8 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting sqlparse>=0.2.2 (from Django>=2.2->-r requirements/requirements.txt (line 1))\n[entity tests/tests]   |   Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 41.2/41.2 kB 3.8 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting django-query-builder>=3.0.1 (from django-manager-utils>=2.0.0->-r requirements/requirements.txt (line 3))\n[entity tests/tests]   |   Downloading django_query_builder-3.0.1-py2.py3-none-any.whl (53 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 53.5/53.5 kB 777.2 kB/s eta 0:00:00\n[entity tests/tests]   | Collecting six>=1.8.0 (from python3-utils>=0.3->-r requirements/requirements.txt (line 5))\n[entity tests/tests]   |   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)\n[entity tests/tests]   | Collecting typing-extensions>=4 (from asgiref<4,>=3.3.2->Django>=2.2->-r requirements/requirements.txt (line 1))\n[entity tests/tests]   |   Downloading typing_extensions-4.6.2-py3-none-any.whl (31 kB)\n[entity tests/tests]   | Collecting fleming>=0.6.0 (from django-query-builder>=3.0.1->django-manager-utils>=2.0.0->-r requirements/requirements.txt (line 3))\n[entity tests/tests]   |   Downloading fleming-0.7.0-py2.py3-none-any.whl (10 kB)\n[entity tests/tests]   | Collecting python-dateutil>=2.2 (from fleming>=0.6.0->django-query-builder>=3.0.1->django-manager-utils>=2.0.0->-r requirements/requirements.txt (line 3))\n[entity tests/tests]   |   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 247.7/247.7 kB 22.9 MB/s eta 0:00:00\n[entity tests/tests]   | Installing collected packages: pytz, wrapt, typing-extensions, sqlparse, six, python3-utils, python-dateutil, asgiref, fleming, Django, jsonfield, django-query-builder, django-manager-utils, django-activatable-model\n[entity tests/tests]   | Successfully installed Django-3.2.19 asgiref-3.7.2 django-activatable-model-3.0.1 django-manager-utils-3.0.1 django-query-builder-3.0.1 fleming-0.7.0 jsonfield-3.1.0 python-dateutil-2.8.2 python3-utils-0.4.0 pytz-2023.3 six-1.16.0 sqlparse-0.4.4 typing-extensions-4.6.2 wrapt-1.15.0\n[entity tests/tests]   | \n[entity tests/tests]   | [notice] A new release of pip is available: 20.1.1 -> 23.1.2\n[entity tests/tests]   | [notice] To update, run: pip install --upgrade pip\n[entity tests/tests]   | Collecting coverage (from -r requirements/requirements-testing.txt (line 1))\n[entity tests/tests]   |   Downloading coverage-7.2.6-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (225 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 225.5/225.5 kB 3.7 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting django-nose (from -r requirements/requirements-testing.txt (line 2))\n[entity tests/tests]   |   Downloading django_nose-1.4.7-py2.py3-none-any.whl (26 kB)\n[entity tests/tests]   | Collecting django-dynamic-fixture (from -r requirements/requirements-testing.txt (line 3))\n[entity tests/tests]   |   Downloading django-dynamic-fixture-3.1.2.tar.gz (41 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 41.2/41.2 kB 1.2 MB/s eta 0:00:00\n[entity tests/tests]   |   Preparing metadata (setup.py): started\n[entity tests/tests]   |   Preparing metadata (setup.py): finished with status 'done'\n[entity tests/tests]   | Collecting mock (from -r requirements/requirements-testing.txt (line 4))\n[entity tests/tests]   |   Downloading mock-5.0.2-py3-none-any.whl (30 kB)\n[entity tests/tests]   | Collecting psycopg2 (from -r requirements/requirements-testing.txt (line 5))\n[entity tests/tests]   |   Downloading psycopg2-2.9.6.tar.gz (383 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 384.0/384.0 kB 5.4 MB/s eta 0:00:00\n[entity tests/tests]   |   Preparing metadata (setup.py): started\n[entity tests/tests]   |   Preparing metadata (setup.py): finished with status 'done'\n[entity tests/tests]   | Collecting flake8 (from -r requirements/requirements-testing.txt (line 6))\n[entity tests/tests]   |   Downloading flake8-5.0.4-py2.py3-none-any.whl (61 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 61.9/61.9 kB 8.7 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting nose>=1.2.1 (from django-nose->-r requirements/requirements-testing.txt (line 2))\n[entity tests/tests]   |   Downloading nose-1.3.7-py3-none-any.whl (154 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 154.7/154.7 kB 2.3 MB/s eta 0:00:00\n[entity tests/tests]   | Requirement already satisfied: six in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (from django-dynamic-fixture->-r requirements/requirements-testing.txt (line 3)) (1.16.0)\n[entity tests/tests]   | Collecting mccabe<0.8.0,>=0.7.0 (from flake8->-r requirements/requirements-testing.txt (line 6))\n[entity tests/tests]   |   Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)\n[entity tests/tests]   | Collecting pycodestyle<2.10.0,>=2.9.0 (from flake8->-r requirements/requirements-testing.txt (line 6))\n[entity tests/tests]   |   Downloading pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 41.5/41.5 kB 1.0 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting pyflakes<2.6.0,>=2.5.0 (from flake8->-r requirements/requirements-testing.txt (line 6))\n[entity tests/tests]   |   Downloading pyflakes-2.5.0-py2.py3-none-any.whl (66 kB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 66.1/66.1 kB 10.8 MB/s eta 0:00:00\n[entity tests/tests]   | Collecting importlib-metadata<4.3,>=1.1.0 (from flake8->-r requirements/requirements-testing.txt (line 6))\n[entity tests/tests]   |   Downloading importlib_metadata-4.2.0-py3-none-any.whl (16 kB)\n[entity tests/tests]   | Collecting zipp>=0.5 (from importlib-metadata<4.3,>=1.1.0->flake8->-r requirements/requirements-testing.txt (line 6))\n[entity tests/tests]   |   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)\n[entity tests/tests]   | Requirement already satisfied: typing-extensions>=3.6.4 in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (from importlib-metadata<4.3,>=1.1.0->flake8->-r requirements/requirements-testing.txt (line 6)) (4.6.2)\n[entity tests/tests]   | Building wheels for collected packages: django-dynamic-fixture, psycopg2\n[entity tests/tests]   |   Building wheel for django-dynamic-fixture (setup.py): started\n[entity tests/tests]   |   Building wheel for django-dynamic-fixture (setup.py): finished with status 'done'\n[entity tests/tests]   |   Created wheel for django-dynamic-fixture: filename=django_dynamic_fixture-3.1.2-py3-none-any.whl size=60674 sha256=a10700437f794fb47cb811793d1204a1399ab151074038649e96a7a0e7b7db67\n[entity tests/tests]   |   Stored in directory: /home/runneradmin/.cache/pip/wheels/90/7b/74/c216118352e9708debad3ad490079e166ceb19bfe30779b7de\n[entity tests/tests]   |   Building wheel for psycopg2 (setup.py): started\n[entity tests/tests]   |   Building wheel for psycopg2 (setup.py): finished with status 'done'\n[entity tests/tests]   |   Created wheel for psycopg2: filename=psycopg2-2.9.6-cp37-cp37m-linux_x86_64.whl size=552377 sha256=c83c6983e1570b62652132c901197012ace314dc9e41bae27be272d2b512befd\n[entity tests/tests]   |   Stored in directory: /home/runneradmin/.cache/pip/wheels/9d/f3/21/cbf320fe8a9661246db7b8e5bacc0362ec111674c8698d03ec\n[entity tests/tests]   | Successfully built django-dynamic-fixture psycopg2\n[entity tests/tests]   | Installing collected packages: nose, zipp, pyflakes, pycodestyle, psycopg2, mock, mccabe, django-nose, django-dynamic-fixture, coverage, importlib-metadata, flake8\n[entity tests/tests]   | Successfully installed coverage-7.2.6 django-dynamic-fixture-3.1.2 django-nose-1.4.7 flake8-5.0.4 importlib-metadata-4.2.0 mccabe-0.7.0 mock-5.0.2 nose-1.3.7 psycopg2-2.9.6 pycodestyle-2.9.1 pyflakes-2.5.0 zipp-3.15.0\n[entity tests/tests]   | \n[entity tests/tests]   | [notice] A new release of pip is available: 20.1.1 -> 23.1.2\n[entity tests/tests]   | [notice] To update, run: pip install --upgrade pip\n[entity tests/tests]   | Collecting Django~=2.2.0\n[entity tests/tests]   |   Downloading Django-2.2.28-py3-none-any.whl (7.5 MB)\n[entity tests/tests]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 7.5/7.5 MB 18.6 MB/s eta 0:00:00\n[entity tests/tests]   | Requirement already satisfied: pytz in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (from Django~=2.2.0) (2023.3)\n[entity tests/tests]   | Requirement already satisfied: sqlparse>=0.2.2 in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (from Django~=2.2.0) (0.4.4)\n[entity tests/tests]   | Installing collected packages: Django\n[entity tests/tests]   |   Attempting uninstall: Django\n[entity tests/tests]   |     Found existing installation: Django 3.2.19\n[entity tests/tests]   |     Uninstalling Django-3.2.19:\n[entity tests/tests]   |       Successfully uninstalled Django-3.2.19\n[entity tests/tests]   | Successfully installed Django-2.2.28\n[entity tests/tests]   | \n[entity tests/tests]   | [notice] A new release of pip is available: 20.1.1 -> 23.1.2\n[entity tests/tests]   | [notice] To update, run: pip install --upgrade pip\n[entity tests/tests]   | asgiref==3.7.2\n[entity tests/tests]   | coverage==7.2.6\n[entity tests/tests]   | Django==2.2.28\n[entity tests/tests]   | django-activatable-model==3.0.1\n[entity tests/tests]   | django-dynamic-fixture==3.1.2\n[entity tests/tests]   | django-manager-utils==3.0.1\n[entity tests/tests]   | django-nose==1.4.7\n[entity tests/tests]   | django-query-builder==3.0.1\n[entity tests/tests]   | flake8==5.0.4\n[entity tests/tests]   | fleming==0.7.0\n[entity tests/tests]   | importlib-metadata==4.2.0\n[entity tests/tests]   | jsonfield==3.1.0\n[entity tests/tests]   | mccabe==0.7.0\n[entity tests/tests]   | mock==5.0.2\n[entity tests/tests]   | nose==1.3.7\n[entity tests/tests]   | psycopg2==2.9.6\n[entity tests/tests]   | pycodestyle==2.9.1\n[entity tests/tests]   | pyflakes==2.5.0\n[entity tests/tests]   | python-dateutil==2.8.2\n[entity tests/tests]   | python3-utils==0.4.0\n[entity tests/tests]   | pytz==2023.3\n[entity tests/tests]   | six==1.16.0\n[entity tests/tests]   | sqlparse==0.4.4\n[entity tests/tests]   | typing_extensions==4.6.2\n[entity tests/tests]   | wrapt==1.15.0\n[entity tests/tests]   | zipp==3.15.0\n[entity tests/tests]   \u2705  Success - Main Setup\n[entity tests/tests] \u2b50 Run Main Run tests\n[entity tests/tests]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=\n[entity tests/tests]   | Creating test database for alias 'default'...\n[entity tests/tests]   | /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py:270: RuntimeWarning: Normally Django will use a connection to the 'postgres' database to avoid running initialization queries against the production database when it's not needed (for example, when running tests). Django was unable to create a connection to the 'postgres' database and will use the first PostgreSQL database instead.\n[entity tests/tests]   |   RuntimeWarning\n[entity tests/tests]   | Traceback (most recent call last):\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 217, in ensure_connection\n[entity tests/tests]   |     self.connect()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 195, in connect\n[entity tests/tests]   |     self.connection = self.get_new_connection(conn_params)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 178, in get_new_connection\n[entity tests/tests]   |     connection = Database.connect(**conn_params)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/psycopg2/__init__.py\", line 122, in connect\n[entity tests/tests]   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n[entity tests/tests]   | psycopg2.OperationalError: could not connect to server: Connection refused\n[entity tests/tests]   | \tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n[entity tests/tests]   | \tTCP/IP connections on port 5432?\n[entity tests/tests]   | could not connect to server: Cannot assign requested address\n[entity tests/tests]   | \tIs the server running on host \"localhost\" (::1) and accepting\n[entity tests/tests]   | \tTCP/IP connections on port 5432?\n[entity tests/tests]   | \n[entity tests/tests]   | \n[entity tests/tests]   | The above exception was the direct cause of the following exception:\n[entity tests/tests]   | \n[entity tests/tests]   | Traceback (most recent call last):\n[entity tests/tests]   |   File \"manage.py\", line 12, in <module>\n[entity tests/tests]   |     execute_from_command_line(sys.argv)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line\n[entity tests/tests]   |     utility.execute()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/core/management/__init__.py\", line 375, in execute\n[entity tests/tests]   |     self.fetch_command(subcommand).run_from_argv(self.argv)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/core/management/commands/test.py\", line 23, in run_from_argv\n[entity tests/tests]   |     super().run_from_argv(argv)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/core/management/base.py\", line 323, in run_from_argv\n[entity tests/tests]   |     self.execute(*args, **cmd_options)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/core/management/base.py\", line 364, in execute\n[entity tests/tests]   |     output = self.handle(*args, **options)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/core/management/commands/test.py\", line 53, in handle\n[entity tests/tests]   |     failures = test_runner.run_tests(test_labels)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django_nose/runner.py\", line 308, in run_tests\n[entity tests/tests]   |     result = self.run_suite(nose_argv)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django_nose/runner.py\", line 245, in run_suite\n[entity tests/tests]   |     addplugins=plugins_to_add)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/core.py\", line 121, in __init__\n[entity tests/tests]   |     **extra_args)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/main.py\", line 101, in __init__\n[entity tests/tests]   |     self.runTests()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/core.py\", line 207, in runTests\n[entity tests/tests]   |     result = self.testRunner.run(self.test)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/core.py\", line 50, in run\n[entity tests/tests]   |     wrapper = self.config.plugins.prepareTest(test)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/plugins/manager.py\", line 99, in __call__\n[entity tests/tests]   |     return self.call(*arg, **kw)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/plugins/manager.py\", line 167, in simple\n[entity tests/tests]   |     result = meth(*arg, **kw)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django_nose/plugin.py\", line 82, in prepareTest\n[entity tests/tests]   |     self.old_names = self.runner.setup_databases()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django_nose/runner.py\", line 491, in setup_databases\n[entity tests/tests]   |     return super(NoseTestSuiteRunner, self).setup_databases()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/test/runner.py\", line 554, in setup_databases\n[entity tests/tests]   |     self.parallel, **kwargs\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/test/utils.py\", line 174, in setup_databases\n[entity tests/tests]   |     serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/creation.py\", line 58, in create_test_db\n[entity tests/tests]   |     self._create_test_db(verbosity, autoclobber, keepdb)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/creation.py\", line 168, in _create_test_db\n[entity tests/tests]   |     with self._nodb_connection.cursor() as cursor:\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 256, in cursor\n[entity tests/tests]   |     return self._cursor()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 233, in _cursor\n[entity tests/tests]   |     self.ensure_connection()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 217, in ensure_connection\n[entity tests/tests]   |     self.connect()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/utils.py\", line 89, in __exit__\n[entity tests/tests]   |     raise dj_exc_value.with_traceback(traceback) from exc_value\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 217, in ensure_connection\n[entity tests/tests]   |     self.connect()\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/base/base.py\", line 195, in connect\n[entity tests/tests]   |     self.connection = self.get_new_connection(conn_params)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/django/db/backends/postgresql/base.py\", line 178, in get_new_connection\n[entity tests/tests]   |     connection = Database.connect(**conn_params)\n[entity tests/tests]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/psycopg2/__init__.py\", line 122, in connect\n[entity tests/tests]   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n[entity tests/tests]   | django.db.utils.OperationalError: could not connect to server: Connection refused\n[entity tests/tests]   | \tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n[entity tests/tests]   | \tTCP/IP connections on port 5432?\n[entity tests/tests]   | could not connect to server: Cannot assign requested address\n[entity tests/tests]   | \tIs the server running on host \"localhost\" (::1) and accepting\n[entity tests/tests]   | \tTCP/IP connections on port 5432?\n[entity tests/tests]   | \n[entity tests/tests]   | nosetests entity --nocapture --nologcapture --verbosity=1\n[entity tests/tests]   \u274c  Failure - Main Run tests\n[entity tests/tests] exitcode '1': failure\n[entity tests/tests] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Job 'tests' failed\n"
}