{
    "repository": "terryyin/translate-python",
    "clone_url": "https://github.com/terryyin/translate-python.git",
    "timestamp": "2023-05-29T14:50:23.808906Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[CI/test] \ud83d\ude80  Start image=crawlergpt:latest\n[CI/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[CI/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[CI/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[CI/test]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[CI/test]   \u2601  git clone 'https://github.com/actions/upload-artifact' # ref=v2\n[CI/test] \ud83e\uddea  Matrix: map[architecture:x64 python-version:3.7]\n[CI/test] \u2b50 Run Main actions/checkout@v2\n[CI/test]   \u2705  Success - Main actions/checkout@v2\n[CI/test] Error response from daemon: No such container: ad0df2502064d1d603a97050c9cdd7b362a8f371d03a7b191555f85b713bc0f3\n[CI/test] \u2b50 Run Main Set up Python 3.7\n[CI/test]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[CI/test]   \u274c  Failure - Main Set up Python 3.7\n[CI/test] Error response from daemon: No such container: ad0df2502064d1d603a97050c9cdd7b362a8f371d03a7b191555f85b713bc0f3\n[CI/test] \u2b50 Run Main actions/upload-artifact@v2\n[CI/test]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-upload-artifact@v2/ dst=/var/run/act/actions/actions-upload-artifact@v2/\n[CI/test]   \u274c  Failure - Main actions/upload-artifact@v2\n[CI/test] Error response from daemon: No such container: ad0df2502064d1d603a97050c9cdd7b362a8f371d03a7b191555f85b713bc0f3\n[CI/test] failed to remove container: Error response from daemon: No such container: ad0df2502064d1d603a97050c9cdd7b362a8f371d03a7b191555f85b713bc0f3\n[CI/test] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Error occurred running finally: Error occurred running finally: Error response from daemon: remove act-CI-test-7587b47f572787ca4bc647c2581a917f05f439a38e66ca9abce9eb5337031daf-env: volume is in use - [91e9b320d25848939833b3f55cb4f70141475f5484047ae677fd37e2c9692d76] (original error: <nil>) (original error: <nil>)\n"
}