{
    "repository": "tomerfiliba-org/rpyc",
    "clone_url": "https://github.com/tomerfiliba-org/rpyc.git",
    "timestamp": "2023-05-29T13:59:33.095739Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[RPyC/python-unittest-all-versions] \ud83d\ude80  Start image=crawlergpt:latest\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/tomerfiliba-org-rpyc] user=0 workdir=\n[RPyC/python-unittest-all-versions]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v4\n[RPyC/python-unittest-all-versions] \ud83e\uddea  Matrix: map[python-version:3.7]\n[RPyC/python-unittest-all-versions] \u2b50 Run Main actions/checkout@v3\n[RPyC/python-unittest-all-versions]   \u2705  Success - Main actions/checkout@v3\n[RPyC/python-unittest-all-versions] \u2b50 Run Main Set up Python 3.7\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v4/ dst=/var/run/act/actions/actions-setup-python@v4/\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v4/] user=0 workdir=\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v4/dist/setup/index.js] user= workdir=\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::Python is expected to be installed into /opt/hostedtoolcache\n[RPyC/python-unittest-all-versions]   \u2753  ::group::Installed versions\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::Semantic version spec of 3.7 is 3.7\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::isExplicit: \n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::explicit? false\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::explicit? true\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::explicit? true\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::explicit? true\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::explicit? true\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::explicit? true\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::explicit? true\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::evaluating 6 versions\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::matched: 3.7.11\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.7.11/x64\n[RPyC/python-unittest-all-versions]   \ud83d\udcac  ::debug::Found tool in cache Python 3.7.11 x64\n[RPyC/python-unittest-all-versions]   | Successfully set up CPython (3.7.11)\n[RPyC/python-unittest-all-versions]   \u2753  ::endgroup::\n[RPyC/python-unittest-all-versions]   \u2753 add-matcher /run/act/actions/actions-setup-python@v4/.github/python.json\n[RPyC/python-unittest-all-versions]   \u2705  Success - Main Set up Python 3.7\n[RPyC/python-unittest-all-versions]   \u2699  ::set-env:: Python2_ROOT_DIR=/opt/hostedtoolcache/Python/3.7.11/x64\n[RPyC/python-unittest-all-versions]   \u2699  ::set-env:: Python3_ROOT_DIR=/opt/hostedtoolcache/Python/3.7.11/x64\n[RPyC/python-unittest-all-versions]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.7.11/x64/lib\n[RPyC/python-unittest-all-versions]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.7.11/x64\n[RPyC/python-unittest-all-versions]   \u2699  ::set-env:: PKG_CONFIG_PATH=/opt/hostedtoolcache/Python/3.7.11/x64/lib/pkgconfig\n[RPyC/python-unittest-all-versions]   \u2699  ::set-env:: Python_ROOT_DIR=/opt/hostedtoolcache/Python/3.7.11/x64\n[RPyC/python-unittest-all-versions]   \u2699  ::set-output:: python-version=3.7.11\n[RPyC/python-unittest-all-versions]   \u2699  ::set-output:: python-path=/opt/hostedtoolcache/Python/3.7.11/x64/bin/python\n[RPyC/python-unittest-all-versions]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64\n[RPyC/python-unittest-all-versions]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.7.11/x64/bin\n[RPyC/python-unittest-all-versions] \u2b50 Run Main Install dependencies\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[RPyC/python-unittest-all-versions]   | Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (21.2.4)\n[RPyC/python-unittest-all-versions]   | Collecting pip\n[RPyC/python-unittest-all-versions]   |   Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)\n[RPyC/python-unittest-all-versions]   | Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages (47.1.0)\n[RPyC/python-unittest-all-versions]   | Collecting setuptools\n[RPyC/python-unittest-all-versions]   |   Downloading setuptools-67.8.0-py3-none-any.whl (1.1 MB)\n[RPyC/python-unittest-all-versions]   | Collecting flake8\n[RPyC/python-unittest-all-versions]   |   Downloading flake8-5.0.4-py2.py3-none-any.whl (61 kB)\n[RPyC/python-unittest-all-versions]   | Collecting pyflakes<2.6.0,>=2.5.0\n[RPyC/python-unittest-all-versions]   |   Downloading pyflakes-2.5.0-py2.py3-none-any.whl (66 kB)\n[RPyC/python-unittest-all-versions]   | Collecting importlib-metadata<4.3,>=1.1.0\n[RPyC/python-unittest-all-versions]   |   Downloading importlib_metadata-4.2.0-py3-none-any.whl (16 kB)\n[RPyC/python-unittest-all-versions]   | Collecting mccabe<0.8.0,>=0.7.0\n[RPyC/python-unittest-all-versions]   |   Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)\n[RPyC/python-unittest-all-versions]   | Collecting pycodestyle<2.10.0,>=2.9.0\n[RPyC/python-unittest-all-versions]   |   Downloading pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)\n[RPyC/python-unittest-all-versions]   | Collecting typing-extensions>=3.6.4\n[RPyC/python-unittest-all-versions]   |   Downloading typing_extensions-4.6.2-py3-none-any.whl (31 kB)\n[RPyC/python-unittest-all-versions]   | Collecting zipp>=0.5\n[RPyC/python-unittest-all-versions]   |   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)\n[RPyC/python-unittest-all-versions]   | Installing collected packages: zipp, typing-extensions, pyflakes, pycodestyle, mccabe, importlib-metadata, setuptools, pip, flake8\n[RPyC/python-unittest-all-versions]   |   Attempting uninstall: setuptools\n[RPyC/python-unittest-all-versions]   |     Found existing installation: setuptools 47.1.0\n[RPyC/python-unittest-all-versions]   |     Uninstalling setuptools-47.1.0:\n[RPyC/python-unittest-all-versions]   |       Successfully uninstalled setuptools-47.1.0\n[RPyC/python-unittest-all-versions]   |   Attempting uninstall: pip\n[RPyC/python-unittest-all-versions]   |     Found existing installation: pip 21.2.4\n[RPyC/python-unittest-all-versions]   |     Uninstalling pip-21.2.4:\n[RPyC/python-unittest-all-versions]   |       Successfully uninstalled pip-21.2.4\n[RPyC/python-unittest-all-versions]   | Successfully installed flake8-5.0.4 importlib-metadata-4.2.0 mccabe-0.7.0 pip-23.1.2 pycodestyle-2.9.1 pyflakes-2.5.0 setuptools-67.8.0 typing-extensions-4.6.2 zipp-3.15.0\n[RPyC/python-unittest-all-versions]   | Collecting plumbum>=1.2 (from -r requirements.txt (line 1))\n[RPyC/python-unittest-all-versions]   |   Downloading plumbum-1.8.1-py3-none-any.whl (126 kB)\n[RPyC/python-unittest-all-versions]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 126.7/126.7 kB 14.5 MB/s eta 0:00:00\n[RPyC/python-unittest-all-versions]   | Installing collected packages: plumbum\n[RPyC/python-unittest-all-versions]   | Successfully installed plumbum-1.8.1\n[RPyC/python-unittest-all-versions]   | \n[RPyC/python-unittest-all-versions]   | [notice] A new release of pip is available: 20.1.1 -> 23.1.2\n[RPyC/python-unittest-all-versions]   | [notice] To update, run: pip install --upgrade pip\n[RPyC/python-unittest-all-versions]   \u2705  Success - Main Install dependencies\n[RPyC/python-unittest-all-versions]   \u2699  ::set-env:: PYTHONPATH=:/home/runner/work/rpyc\n[RPyC/python-unittest-all-versions] \u2b50 Run Main Lint with flake8\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=\n[RPyC/python-unittest-all-versions]   | 0\n[RPyC/python-unittest-all-versions]   | ./bin/rpyc_classic.py:2:1: F403 'from rpyc.cli.rpyc_classic import *' used; unable to detect undefined names\n[RPyC/python-unittest-all-versions]   | ./bin/rpyc_classic.py:6:5: F405 'main' may be undefined, or defined from star imports: rpyc.cli.rpyc_classic\n[RPyC/python-unittest-all-versions]   | ./bin/rpyc_registry.py:2:1: F403 'from rpyc.cli.rpyc_registry import *' used; unable to detect undefined names\n[RPyC/python-unittest-all-versions]   | ./bin/rpyc_registry.py:6:5: F405 'main' may be undefined, or defined from star imports: rpyc.cli.rpyc_registry\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:22:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:27:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:40:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:54:1: E402 module level import not at top of file\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:61:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:65:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:67:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:74:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:77:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:81:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:85:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:91:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:100:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:101:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:103:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:112:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:116:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:117:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:121:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:139:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:143:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:146:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:150:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:159:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:165:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:168:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:173:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:176:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:185:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:188:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:199:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:203:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:206:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:209:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:212:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:215:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./docs/conf.py:218:1: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./demos/echo/server.py:2:1: F401 'inspect' imported but unused\n[RPyC/python-unittest-all-versions]   | ./demos/async_client/server.py:6:1: F401 'logging' imported but unused\n[RPyC/python-unittest-all-versions]   | ./demos/async_client/server.py:9:1: F401 'threading' imported but unused\n[RPyC/python-unittest-all-versions]   | ./demos/async_client/client.py:38:5: F841 local variable 'value' is assigned to but never used\n[RPyC/python-unittest-all-versions]   | ./tests/test_teleportation.py:3:1: F401 'rpyc.lib.compat.is_py_3k' imported but unused\n[RPyC/python-unittest-all-versions]   | ./tests/test_netref_hierachy.py:48:90: W291 trailing whitespace\n[RPyC/python-unittest-all-versions]   | ./tests/test_get_id_pack.py:33:9: F841 local variable 'remote_os' is assigned to but never used\n[RPyC/python-unittest-all-versions]   | ./tests/__init__.py:2:1: F401 'rpyc' imported but unused\n[RPyC/python-unittest-all-versions]   | ./tests/__init__.py:5:1: E302 expected 2 blank lines, found 1\n[RPyC/python-unittest-all-versions]   | ./tests/__init__.py:7:5: E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | ./tests/test_race.py:32:13: E731 do not assign a lambda expression, use a def\n[RPyC/python-unittest-all-versions]   | ./rpyc/core/protocol.py:370:9: E722 do not use bare 'except'\n[RPyC/python-unittest-all-versions]   | ./rpyc/core/protocol.py:449:128: E501 line too long (134 > 127 characters)\n[RPyC/python-unittest-all-versions]   | ./rpyc/core/protocol.py:481:5: C901 'Connection._serve_bound' is too complex (29)\n[RPyC/python-unittest-all-versions]   | ./rpyc/core/async_.py:2:1: F401 'threading.Event' imported but unused\n[RPyC/python-unittest-all-versions]   | ./rpyc/core/vinegar.py:32:1: C901 'dump' is too complex (13)\n[RPyC/python-unittest-all-versions]   | ./rpyc/core/vinegar.py:85:1: C901 'load' is too complex (18)\n[RPyC/python-unittest-all-versions]   | ./rpyc/cli/rpyc_classic.py:65:5: C901 'ClassicServer.main' is too complex (11)\n[RPyC/python-unittest-all-versions]   | ./rpyc/lib/compat.py:96:1: C901 'If 96' is too complex (24)\n[RPyC/python-unittest-all-versions]   | ./rpyc/utils/registry.py:2:128: E501 line too long (332 > 127 characters)\n[RPyC/python-unittest-all-versions]   | ./rpyc/utils/registry.py:5:128: E501 line too long (184 > 127 characters)\n[RPyC/python-unittest-all-versions]   | ./rpyc/utils/classic.py:5:1: F401 'rpyc.lib.compat.execute' imported but unused\n[RPyC/python-unittest-all-versions]   | ./rpyc/utils/zerodeploy.py:91:5: C901 'DeployedServer.__init__' is too complex (12)\n[RPyC/python-unittest-all-versions]   | ./rpyc/utils/zerodeploy.py:155:5: C901 'DeployedServer.close' is too complex (16)\n[RPyC/python-unittest-all-versions]   | 7     C901 'ClassicServer.main' is too complex (11)\n[RPyC/python-unittest-all-versions]   | 37    E265 block comment should start with '# '\n[RPyC/python-unittest-all-versions]   | 1     E302 expected 2 blank lines, found 1\n[RPyC/python-unittest-all-versions]   | 1     E402 module level import not at top of file\n[RPyC/python-unittest-all-versions]   | 3     E501 line too long (134 > 127 characters)\n[RPyC/python-unittest-all-versions]   | 1     E722 do not use bare 'except'\n[RPyC/python-unittest-all-versions]   | 1     E731 do not assign a lambda expression, use a def\n[RPyC/python-unittest-all-versions]   | 7     F401 'logging' imported but unused\n[RPyC/python-unittest-all-versions]   | 2     F403 'from rpyc.cli.rpyc_classic import *' used; unable to detect undefined names\n[RPyC/python-unittest-all-versions]   | 2     F405 'main' may be undefined, or defined from star imports: rpyc.cli.rpyc_classic\n[RPyC/python-unittest-all-versions]   | 2     F841 local variable 'value' is assigned to but never used\n[RPyC/python-unittest-all-versions]   | 1     W291 trailing whitespace\n[RPyC/python-unittest-all-versions]   | 65\n[RPyC/python-unittest-all-versions]   \u2705  Success - Main Lint with flake8\n[RPyC/python-unittest-all-versions] \u2b50 Run Main Init ssh settings\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=\n[RPyC/python-unittest-all-versions]   | mkdir: created directory '/home/runneradmin/.ssh'\n[RPyC/python-unittest-all-versions]   | Linux 19e40336fd70 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux\n[RPyC/python-unittest-all-versions]   \u2705  Success - Main Init ssh settings\n[RPyC/python-unittest-all-versions] \u2b50 Run Main Bind threads tests with unittest\n[RPyC/python-unittest-all-versions]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=\n[RPyC/python-unittest-all-versions]   | test_pinned_to_0 (tests.test_affinity.Test_Affinity)\n[RPyC/python-unittest-all-versions]   | test behavior with processor affinity set such that this process is pinned to 0 ... ok\n[RPyC/python-unittest-all-versions]   | test_asyncresult_api (tests.test_async.TestAsync) ... ok\n[RPyC/python-unittest-all-versions]   | test_asyncresult_callbacks (tests.test_async.TestAsync) ... ok\n[RPyC/python-unittest-all-versions]   | test_asyncresult_expiry (tests.test_async.TestAsync) ... ok\n[RPyC/python-unittest-all-versions]   | test_exceptions (tests.test_async.TestAsync) ... ok\n[RPyC/python-unittest-all-versions]   | test_timed (tests.test_async.TestAsync) ... ok\n[RPyC/python-unittest-all-versions]   | test_allow_all (tests.test_attr_access.TestConfigAllows) ... ok\n[RPyC/python-unittest-all-versions]   | test_allow_exposed (tests.test_attr_access.TestConfigAllows) ... ok\n[RPyC/python-unittest-all-versions]   | test_allow_public_attrs (tests.test_attr_access.TestConfigAllows) ... ok\n[RPyC/python-unittest-all-versions]   | test_allow_safe_attrs (tests.test_attr_access.TestConfigAllows) ... ok\n[RPyC/python-unittest-all-versions]   | test_default_config (tests.test_attr_access.TestConfigAllows) ... ok\n[RPyC/python-unittest-all-versions]   | test_allow_all (tests.test_attr_access.TestDescriptorErrors) ... ok\n[RPyC/python-unittest-all-versions]   | test_default_config (tests.test_attr_access.TestDescriptorErrors) ... ok\n[RPyC/python-unittest-all-versions]   | test_restricted (tests.test_attr_access.TestRestricted) ... ok\n[RPyC/python-unittest-all-versions]   | test_restricted2 (tests.test_attr_access.TestRestricted) ... ok\n[RPyC/python-unittest-all-versions]   | test_properties (tests.test_attributes.TestAttributes) ... ok\n[RPyC/python-unittest-all-versions]   | test_brine_2 (tests.test_brine.BrineTest) ... ok\n[RPyC/python-unittest-all-versions]   | test_buffiter (tests.test_classic.ClassicMode) ... ok\n[RPyC/python-unittest-all-versions]   | test_classic (tests.test_classic.ClassicMode) ... ok\n[RPyC/python-unittest-all-versions]   | test_mock_connection (tests.test_classic.ClassicMode) ... ok\n[RPyC/python-unittest-all-versions]   | test_modules (tests.test_classic.ClassicMode) ... ok\n[RPyC/python-unittest-all-versions]   | test_piped_server (tests.test_classic.ClassicMode) ... ok\n[RPyC/python-unittest-all-versions]   | test_context (tests.test_context_managers.TestContextManagers) ... ok\n[RPyC/python-unittest-all-versions]   | test_context_exception (tests.test_context_managers.TestContextManagers) ... ok\n[RPyC/python-unittest-all-versions]   | test_aliases (tests.test_custom_service.TestCustomService) ... ok\n[RPyC/python-unittest-all-versions]   | test_attributes (tests.test_custom_service.TestCustomService) ... ok\n[RPyC/python-unittest-all-versions]   | test_before_closed (tests.test_custom_service.TestCustomService) ... ok\n[RPyC/python-unittest-all-versions]   | test_distance (tests.test_custom_service.TestCustomService) ... ok\n[RPyC/python-unittest-all-versions]   | test_instancecheck_list (tests.test_custom_service.TestCustomService) ... ok\n[RPyC/python-unittest-all-versions]   | test_metaclasses (tests.test_custom_service.TestCustomService) ... ok\n[RPyC/python-unittest-all-versions]   | test_safeattrs (tests.test_custom_service.TestCustomService) ... ok\n[RPyC/python-unittest-all-versions]   | test_remote_dataclass (tests.test_dataclass.TestRemoteDataclass) ... ok\n[RPyC/python-unittest-all-versions]   | test_close_timeout (tests.test_deploy.TestDeploy) ... ERROR\n[RPyC/python-unittest-all-versions]   | /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/case.py:656: ResourceWarning: unclosed file <_io.BufferedWriter name=4>\n[RPyC/python-unittest-all-versions]   |   outcome.errors.clear()\n[RPyC/python-unittest-all-versions]   | Object allocated at (most recent call last):\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/subprocess.py\", lineno 778\n[RPyC/python-unittest-all-versions]   |     self.stdin = io.open(p2cwrite, 'wb', bufsize)\n[RPyC/python-unittest-all-versions]   | /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/case.py:656: ResourceWarning: unclosed file <_io.BufferedReader name=5>\n[RPyC/python-unittest-all-versions]   |   outcome.errors.clear()\n[RPyC/python-unittest-all-versions]   | Object allocated at (most recent call last):\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/subprocess.py\", lineno 784\n[RPyC/python-unittest-all-versions]   |     self.stdout = io.open(c2pread, 'rb', bufsize)\n[RPyC/python-unittest-all-versions]   | /opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/case.py:656: ResourceWarning: unclosed file <_io.BufferedReader name=7>\n[RPyC/python-unittest-all-versions]   |   outcome.errors.clear()\n[RPyC/python-unittest-all-versions]   | Object allocated at (most recent call last):\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/subprocess.py\", lineno 789\n[RPyC/python-unittest-all-versions]   |     self.stderr = io.open(errread, 'rb', bufsize)\n[RPyC/python-unittest-all-versions]   | test_close_timeout_default_none (tests.test_deploy.TestDeploy) ... ERROR\n[RPyC/python-unittest-all-versions]   | test_deploy (tests.test_deploy.TestDeploy) ... ERROR\n[RPyC/python-unittest-all-versions]   | test_deploy_paramiko (tests.test_deploy.TestDeploy) ... skipped 'Paramiko is not available'\n[RPyC/python-unittest-all-versions]   | test_gdb (tests.test_gdb.Test_GDB) ... skipped 'Skipping gdb example test since gdb not found'\n[RPyC/python-unittest-all-versions]   | test_chained_connect (tests.test_get_id_pack.Test_get_id_pack) ... ok\n[RPyC/python-unittest-all-versions]   | test_class_instance_wo_name (tests.test_get_id_pack.Test_get_id_pack) ... ok\n[RPyC/python-unittest-all-versions]   | test_class_wo_name (tests.test_get_id_pack.Test_get_id_pack) ... ok\n[RPyC/python-unittest-all-versions]   | test_netref (tests.test_get_id_pack.Test_get_id_pack) ... ok\n[RPyC/python-unittest-all-versions]   | test_connection (tests.test_gevent_server.Test_GeventServer) ... skipped 'Gevent is not available'\n[RPyC/python-unittest-all-versions]   | test_multiple_connections (tests.test_gevent_server.Test_GeventServer) ... skipped 'Gevent is not available'\n[RPyC/python-unittest-all-versions]   | test_parallelism (tests.test_gevent_server.Test_GeventServer) ... skipped 'Gevent is not available'\n[RPyC/python-unittest-all-versions]   | test_ipv6_conenction (tests.test_ipv6.Test_IPv6) ... skipped 'requires IPv6'\n[RPyC/python-unittest-all-versions]   | test_hash_class (tests.test_magic.TestContextManagers) ... ok\n[RPyC/python-unittest-all-versions]   | test_hash_obj (tests.test_magic.TestContextManagers) ... ok\n[RPyC/python-unittest-all-versions]   | test_StandardError (tests.test_netref_hierachy.Test_Netref_Hierarchy) ... ok\n[RPyC/python-unittest-all-versions]   | test_classic (tests.test_netref_hierachy.Test_Netref_Hierarchy) ... ok\n[RPyC/python-unittest-all-versions]   | test_instancecheck_across_connections (tests.test_netref_hierachy.Test_Netref_Hierarchy) ... ok\n[RPyC/python-unittest-all-versions]   | test_instancecheck_list (tests.test_netref_hierachy.Test_Netref_Hierarchy) ... ok\n[RPyC/python-unittest-all-versions]   | test_instancecheck_none (tests.test_netref_hierachy.Test_Netref_Hierarchy)\n[RPyC/python-unittest-all-versions]   | test for the regression reported in https://github.com/tomerfiliba-org/rpyc/issues/426 ... ok\n[RPyC/python-unittest-all-versions]   | test_modules (tests.test_netref_hierachy.Test_Netref_Hierarchy)\n[RPyC/python-unittest-all-versions]   | >>> type(sys) ... ok\n[RPyC/python-unittest-all-versions]   | test_server_stops (tests.test_oneshot_server.Test_OneShotServer) ... ok\n[RPyC/python-unittest-all-versions]   | test_asyncresult_race (tests.test_race.TestRace) ... ok\n[RPyC/python-unittest-all-versions]   | test_refcount (tests.test_refcount.TestRefcount) ... ok\n[RPyC/python-unittest-all-versions]   | test_api (tests.test_registry.TestTcpRegistry) ... ok\n[RPyC/python-unittest-all-versions]   | test_listing (tests.test_registry.TestTcpRegistry) ... ok\n[RPyC/python-unittest-all-versions]   | test_pruning (tests.test_registry.TestTcpRegistry) ... ok\n[RPyC/python-unittest-all-versions]   | test_api (tests.test_registry.TestUdpRegistry) ... ok\n[RPyC/python-unittest-all-versions]   | test_listing (tests.test_registry.TestUdpRegistry) ... ok\n[RPyC/python-unittest-all-versions]   | test_pruning (tests.test_registry.TestUdpRegistry) ... ok\n[RPyC/python-unittest-all-versions]   | test_remote_exception (tests.test_remote_exception.TestExclusionsRemoteException) ... ok\n[RPyC/python-unittest-all-versions]   | test_remote_exception (tests.test_remote_exception.TestRemoteException) ... ok\n[RPyC/python-unittest-all-versions]   | test_distribution (tests.test_remoting.Test_Remoting) ... skipped 'TODO: upload a package and a module'\n[RPyC/python-unittest-all-versions]   | test_files (tests.test_remoting.Test_Remoting) ... ok\n[RPyC/python-unittest-all-versions]   | test_interactive (tests.test_remoting.Test_Remoting) ... skipped 'Requires manual testing atm'\n[RPyC/python-unittest-all-versions]   | test_migration (tests.test_remoting.Test_Remoting) ... ok\n[RPyC/python-unittest-all-versions]   | test_post_mortem (tests.test_remoting.Test_Remoting) ... skipped 'Requires manual testing atm'\n[RPyC/python-unittest-all-versions]   | test_immutable_object_return (tests.test_rpyc_over_rpyc.Test_rpyc_over_rpyc)\n[RPyC/python-unittest-all-versions]   | Tests using rpyc over rpyc---issue #346 reported traceback for this use case ... ok\n[RPyC/python-unittest-all-versions]   | test_return_of_modified_parameter (tests.test_rpyc_over_rpyc.Test_rpyc_over_rpyc) ... ok\n[RPyC/python-unittest-all-versions]   | test_return_of_unmodified_parameter (tests.test_rpyc_over_rpyc.Test_rpyc_over_rpyc) ... ok\n[RPyC/python-unittest-all-versions]   | test_dataframe_pickling (tests.test_service_pickle.TestServicePickle) ... skipped 'Pandas & numpy are not available'\n[RPyC/python-unittest-all-versions]   | test_connect (tests.test_ssh.Test_Ssh) ... skipped 'Requires paramiko_machine to localhost'\n[RPyC/python-unittest-all-versions]   | test_simple (tests.test_ssh.Test_Ssh) ... skipped 'Requires paramiko_machine to localhost'\n[RPyC/python-unittest-all-versions]   | test_ssl_conenction (tests.test_ssl.Test_SSL) ... ok\n[RPyC/python-unittest-all-versions]   | test (tests.test_teleportation.TeleportationTest) ... ok\n[RPyC/python-unittest-all-versions]   | test_compat (tests.test_teleportation.TeleportationTest) ... ok\n[RPyC/python-unittest-all-versions]   | test_def (tests.test_teleportation.TeleportationTest) ... ok\n[RPyC/python-unittest-all-versions]   | test_defaults (tests.test_teleportation.TeleportationTest) ... ok\n[RPyC/python-unittest-all-versions]   | test_globals (tests.test_teleportation.TeleportationTest) ... ok\n[RPyC/python-unittest-all-versions]   | test_kwdefaults (tests.test_teleportation.TeleportationTest) ... ok\n[RPyC/python-unittest-all-versions]   | test_connection (tests.test_threaded_server.Test_ThreadPoolServer) ... ok\n[RPyC/python-unittest-all-versions]   | test_connection (tests.test_threaded_server.Test_ThreadedServer) ... ok\n[RPyC/python-unittest-all-versions]   | test_connection (tests.test_threaded_server.Test_ThreadedServerOverUnixSocket) ... ok\n[RPyC/python-unittest-all-versions]   | test_invoker (tests.test_threads.Test_Multithreaded) ... ok\n[RPyC/python-unittest-all-versions]   | test_basic_io (tests.test_win32pipes.Test_Pipes) ... skipped 'Requires windows'\n[RPyC/python-unittest-all-versions]   | test_rpyc (tests.test_win32pipes.Test_Pipes) ... skipped 'Requires windows'\n[RPyC/python-unittest-all-versions]   | \n[RPyC/python-unittest-all-versions]   | ======================================================================\n[RPyC/python-unittest-all-versions]   | ERROR: test_close_timeout (tests.test_deploy.TestDeploy)\n[RPyC/python-unittest-all-versions]   | ----------------------------------------------------------------------\n[RPyC/python-unittest-all-versions]   | Traceback (most recent call last):\n[RPyC/python-unittest-all-versions]   |   File \"/tmp/de65f406-fe28-11ed-a890-af2cc187fc11/tomerfiliba-org-rpyc/tests/test_deploy.py\", line 49, in test_close_timeout\n[RPyC/python-unittest-all-versions]   |     rem = SshMachine(\"localhost\")\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py\", line 164, in __init__\n[RPyC/python-unittest-all-versions]   |     new_session=new_session,\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/remote.py\", line 172, in __init__\n[RPyC/python-unittest-all-versions]   |     self._session = self.session(new_session=new_session)\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py\", line 249, in session\n[RPyC/python-unittest-all-versions]   |     host=self.host,\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 233, in __init__\n[RPyC/python-unittest-all-versions]   |     self._startup_result = self.run(\"\")\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 319, in run\n[RPyC/python-unittest-all-versions]   |     return run_proc(self.popen(cmd), retcode)\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/commands/processes.py\", line 294, in run_proc\n[RPyC/python-unittest-all-versions]   |     stdout, stderr = proc.communicate()\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 156, in communicate\n[RPyC/python-unittest-all-versions]   |     ) from None\n[RPyC/python-unittest-all-versions]   | plumbum.machines.session.SSHCommsError: SSH communication failed\n[RPyC/python-unittest-all-versions]   | Return code:  | None\n[RPyC/python-unittest-all-versions]   | Command line: | 'true '\n[RPyC/python-unittest-all-versions]   | Host:         | localhost\n[RPyC/python-unittest-all-versions]   | Stderr:       | ssh: connect to host localhost port 22: Cannot assign requested address\n[RPyC/python-unittest-all-versions]   | \n[RPyC/python-unittest-all-versions]   | ======================================================================\n[RPyC/python-unittest-all-versions]   | ERROR: test_close_timeout_default_none (tests.test_deploy.TestDeploy)\n[RPyC/python-unittest-all-versions]   | ----------------------------------------------------------------------\n[RPyC/python-unittest-all-versions]   | Traceback (most recent call last):\n[RPyC/python-unittest-all-versions]   |   File \"/tmp/de65f406-fe28-11ed-a890-af2cc187fc11/tomerfiliba-org-rpyc/tests/test_deploy.py\", line 73, in test_close_timeout_default_none\n[RPyC/python-unittest-all-versions]   |     rem = SshMachine(\"localhost\")\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py\", line 164, in __init__\n[RPyC/python-unittest-all-versions]   |     new_session=new_session,\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/remote.py\", line 172, in __init__\n[RPyC/python-unittest-all-versions]   |     self._session = self.session(new_session=new_session)\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py\", line 249, in session\n[RPyC/python-unittest-all-versions]   |     host=self.host,\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 233, in __init__\n[RPyC/python-unittest-all-versions]   |     self._startup_result = self.run(\"\")\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 319, in run\n[RPyC/python-unittest-all-versions]   |     return run_proc(self.popen(cmd), retcode)\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/commands/processes.py\", line 294, in run_proc\n[RPyC/python-unittest-all-versions]   |     stdout, stderr = proc.communicate()\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 156, in communicate\n[RPyC/python-unittest-all-versions]   |     ) from None\n[RPyC/python-unittest-all-versions]   | plumbum.machines.session.SSHCommsError: SSH communication failed\n[RPyC/python-unittest-all-versions]   | Return code:  | None\n[RPyC/python-unittest-all-versions]   | Command line: | 'true '\n[RPyC/python-unittest-all-versions]   | Host:         | localhost\n[RPyC/python-unittest-all-versions]   | Stderr:       | ssh: connect to host localhost port 22: Cannot assign requested address\n[RPyC/python-unittest-all-versions]   | \n[RPyC/python-unittest-all-versions]   | ======================================================================\n[RPyC/python-unittest-all-versions]   | ERROR: test_deploy (tests.test_deploy.TestDeploy)\n[RPyC/python-unittest-all-versions]   | ----------------------------------------------------------------------\n[RPyC/python-unittest-all-versions]   | Traceback (most recent call last):\n[RPyC/python-unittest-all-versions]   |   File \"/tmp/de65f406-fe28-11ed-a890-af2cc187fc11/tomerfiliba-org-rpyc/tests/test_deploy.py\", line 20, in test_deploy\n[RPyC/python-unittest-all-versions]   |     rem = SshMachine(\"localhost\")\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py\", line 164, in __init__\n[RPyC/python-unittest-all-versions]   |     new_session=new_session,\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/remote.py\", line 172, in __init__\n[RPyC/python-unittest-all-versions]   |     self._session = self.session(new_session=new_session)\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/ssh_machine.py\", line 249, in session\n[RPyC/python-unittest-all-versions]   |     host=self.host,\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 233, in __init__\n[RPyC/python-unittest-all-versions]   |     self._startup_result = self.run(\"\")\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 319, in run\n[RPyC/python-unittest-all-versions]   |     return run_proc(self.popen(cmd), retcode)\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/commands/processes.py\", line 294, in run_proc\n[RPyC/python-unittest-all-versions]   |     stdout, stderr = proc.communicate()\n[RPyC/python-unittest-all-versions]   |   File \"/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/plumbum/machines/session.py\", line 156, in communicate\n[RPyC/python-unittest-all-versions]   |     ) from None\n[RPyC/python-unittest-all-versions]   | plumbum.machines.session.SSHCommsError: SSH communication failed\n[RPyC/python-unittest-all-versions]   | Return code:  | None\n[RPyC/python-unittest-all-versions]   | Command line: | 'true '\n[RPyC/python-unittest-all-versions]   | Host:         | localhost\n[RPyC/python-unittest-all-versions]   | Stderr:       | ssh: connect to host localhost port 22: Cannot assign requested address\n[RPyC/python-unittest-all-versions]   | \n[RPyC/python-unittest-all-versions]   | ----------------------------------------------------------------------\n[RPyC/python-unittest-all-versions]   | Ran 88 tests in 63.581s\n[RPyC/python-unittest-all-versions]   | \n[RPyC/python-unittest-all-versions]   | FAILED (errors=3, skipped=14)\n[RPyC/python-unittest-all-versions]   | 1\n[RPyC/python-unittest-all-versions]   | 2\n[RPyC/python-unittest-all-versions]   | 3\n[RPyC/python-unittest-all-versions]   | service name: MY\n[RPyC/python-unittest-all-versions]   | <tests.test_custom_service.MyClass object at 0x7fe38c333dd0>\n[RPyC/python-unittest-all-versions]   | /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/tomerfiliba-org-rpyc/tests/server.crt /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/tomerfiliba-org-rpyc/tests/server.key\n[RPyC/python-unittest-all-versions]   | <rpyc.core.protocol.Connection 'conn142' object at 0x7fe38c534c90>\n[RPyC/python-unittest-all-versions]   | <module 'sys' (built-in)>\n[RPyC/python-unittest-all-versions]   | <xml.dom.minidom.Document object at 0x7fe38de1ff30>\n[RPyC/python-unittest-all-versions]   | <module 'sys' (built-in)>\n[RPyC/python-unittest-all-versions]   | <xml.dom.minidom.Document object at 0x7fe38dcb2520>\n[RPyC/python-unittest-all-versions]   | <module 'sys' (built-in)>\n[RPyC/python-unittest-all-versions]   | <xml.dom.minidom.Document object at 0x7fe38dcb23d0>\n[RPyC/python-unittest-all-versions]   | <module 'sys' (built-in)>\n[RPyC/python-unittest-all-versions]   | <xml.dom.minidom.Document object at 0x7fe38de1ade0>\n[RPyC/python-unittest-all-versions]   | callback 1685368875.6641178\n[RPyC/python-unittest-all-versions]   | callback 1685368876.6648734\n[RPyC/python-unittest-all-versions]   | foo0 = 0\n[RPyC/python-unittest-all-versions]   | callback 1685368877.6664786\n[RPyC/python-unittest-all-versions]   | callback 1685368878.668\n[RPyC/python-unittest-all-versions]   | callback 1685368879.6688602\n[RPyC/python-unittest-all-versions]   | foo1 = 17\n[RPyC/python-unittest-all-versions]   | callback 1685368880.6703415\n[RPyC/python-unittest-all-versions]   | callback 1685368881.671788\n[RPyC/python-unittest-all-versions]   | foo2 = 34\n[RPyC/python-unittest-all-versions]   | callback called 7 times\n[RPyC/python-unittest-all-versions]   \u274c  Failure - Main Bind threads tests with unittest\n[RPyC/python-unittest-all-versions] exitcode '1': failure\n[RPyC/python-unittest-all-versions] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Job 'python-unittest-all-versions' failed\n"
}