{
    "repository": "chipsec/chipsec",
    "clone_url": "https://github.com/chipsec/chipsec.git",
    "timestamp": "2023-05-29T15:19:46.742635Z",
    "clone_success": true,
    "number of actions": 2,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Run tests/Windows driver     ] \ud83d\ude80  Start image=crawlergpt:latest\n[Run tests/Test on Ubuntu     ] \ud83d\ude80  Start image=node:16-bullseye-slim\n[Run tests/Linux kernel module] \ud83d\ude80  Start image=docker://docker.io/library/alpine:3.17\n[Run tests/Linux kernel module]   \ud83d\udc33  docker pull image=docker://docker.io/library/alpine:3.17 platform= username= forcePull=false\n[Run tests/Test on Ubuntu     ]   \ud83d\udc33  docker pull image=node:16-bullseye-slim platform= username= forcePull=false\n[Run tests/Windows driver     ]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Run tests/Windows driver     ]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Run tests/Test on Ubuntu     ]   \ud83d\udc33  docker create image=node:16-bullseye-slim platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Run tests/Test on Ubuntu     ]   \ud83d\udc33  docker run image=node:16-bullseye-slim platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Run tests/Windows driver     ]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Run tests/Test on Ubuntu     ]   \ud83d\udc33  docker exec cmd=[chown -R 1012:0 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/chipsec-chipsec] user=0 workdir=\n[Run tests/Windows driver     ]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/chipsec-chipsec] user=0 workdir=\n[Run tests/Windows driver     ]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v4\n[Run tests/Windows driver     ] Unable to reset to bd6b4b6205c4dbad673328db7b31b7fab9e241c0: unexpected EOF\n[Run tests/Test on Ubuntu     ]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v4\n[Run tests/Test on Ubuntu     ] Unable to reset to bd6b4b6205c4dbad673328db7b31b7fab9e241c0: EOF\n[Run tests/Test on Ubuntu     ] \ud83c\udfc1  Job succeeded\n[Run tests/Windows driver     ] \ud83c\udfc1  Job succeeded\n",
    "actions_stderr": "Error: unable to determine if image already exists for image 'docker://docker.io/library/alpine:3.17' (): Error response from daemon: no such image: docker:/docker.io/library/alpine:3.17: invalid reference format\n"
}