{
    "repository": "saxix/django-concurrency",
    "clone_url": "https://github.com/saxix/django-concurrency.git",
    "timestamp": "2023-05-29T14:24:47.545670Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Test/lint] \ud83d\ude80  Start image=crawlergpt:latest\n[Test/test] \ud83d\ude80  Start image=crawlergpt:latest\n[Test/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Test/lint]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Test/lint]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Test/test] failed to remove container: Error response from daemon: removal of container aff9c7fa69398eb778e6492e2be9221a04b220d7cbd04843feee1236923536b7 is already in progress\n[Test/lint]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Test/lint]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/saxix-django-concurrency] user=0 workdir=\n[Test/lint]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[Test/lint] Unable to reset to 75f3110429a8c05be0e1bf360334e4cced2b63fa: EOF\n[Test/lint] \ud83c\udfc1  Job succeeded\n",
    "actions_stderr": "Error: Error response from daemon: remove act-Test-test-1a89228c479b352e9beafd139ce1652ef6d39e9a57114fb000a3c158cff408d6-env: volume is in use - [aff9c7fa69398eb778e6492e2be9221a04b220d7cbd04843feee1236923536b7]\n"
}