{
    "repository": "alanjds/drf-nested-routers",
    "clone_url": "https://github.com/alanjds/drf-nested-routers.git",
    "timestamp": "2023-05-29T15:03:08.525039Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[CI/test] \ud83d\ude80  Start image=crawlergpt:latest\n[CI/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[CI/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[CI/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[CI/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/alanjds-drf-nested-routers] user=0 workdir=\n[CI/test]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[CI/test] \ud83e\uddea  Matrix: map[python-version:3.7]\n[CI/test] \u2b50 Run Main actions/checkout@v3\n[CI/test]   \u2705  Success - Main actions/checkout@v3\n[CI/test] \u2b50 Run Main Set up Python 3.7\n[CI/test]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[CI/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v2/] user=0 workdir=\n[CI/test]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/setup/index.js] user= workdir=\n[CI/test]   | OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown\r\n[CI/test]   \u274c  Failure - Main Set up Python 3.7\n[CI/test] Error response from daemon: Could not find the file /var/run/act/workflow/pathcmd.txt in container dfa464cbe98b00a1203f0f34c94538132e8b896c7062234e3fab582795cd7430\n[CI/test] failed to remove container: Error response from daemon: No such container: dfa464cbe98b00a1203f0f34c94538132e8b896c7062234e3fab582795cd7430\n[CI/test] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Error occurred running finally: Error occurred running finally: Error response from daemon: remove act-CI-test-7587b47f572787ca4bc647c2581a917f05f439a38e66ca9abce9eb5337031daf-env: volume is in use - [3b049e531cc6a3ac593211038253f2a6359c763a660bb3579e10254e907f57b4] (original error: <nil>) (original error: <nil>)\n"
}