{
    "repository": "amolenaar/roles",
    "clone_url": "https://github.com/amolenaar/roles.git",
    "timestamp": "2023-05-29T14:00:22.134246Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[build/lint] \ud83d\ude80  Start image=crawlergpt:latest\n[build/lint]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[build/lint]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[build/lint]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[build/lint]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/amolenaar-roles] user=0 workdir=\n[build/lint]   \u2601  git clone 'https://github.com/actions/checkout' # ref=v2\n[build/lint]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2.1.4\n[build/lint]   \u2601  git clone 'https://github.com/pre-commit/action' # ref=v2.0.0\n[build/lint] \u2b50 Run Main actions/checkout@v2\n[build/lint]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-checkout@v2/ dst=/var/run/act/actions/actions-checkout@v2/\n[build/lint]   \u274c  Failure - Main actions/checkout@v2\n[build/lint] Error response from daemon: No such container: e86cab56db74ea41293be0314a2dfdeb12994147610e7f6b6ed0e0b93e5fc32a\n[build/lint] \u2b50 Run Post actions/checkout@v2\n[build/lint]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-checkout@v2/dist/index.js] user= workdir=\n[build/lint]   \u274c  Failure - Post actions/checkout@v2\n[build/lint] failed to remove container: Error response from daemon: No such container: e86cab56db74ea41293be0314a2dfdeb12994147610e7f6b6ed0e0b93e5fc32a\n[build/lint] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Error occurred running finally: Error occurred running finally: Error response from daemon: remove act-build-lint-c5700a073eb4232a38927782756eede5bc7f872d3e0a2afcede0820091e0b48b-env: volume is in use - [251725fdbc803c3dc5890f39e941d8c3a5eda52afa904678d2b31f99d0356277] (original error: Error occurred running finally: Error occurred running finally: Error response from daemon: No such container: e86cab56db74ea41293be0314a2dfdeb12994147610e7f6b6ed0e0b93e5fc32a (original error: <nil>) (original error: <nil>)) (original error: <nil>)\n"
}