{
    "repository": "DinoTools/python-overpy",
    "clone_url": "https://github.com/DinoTools/python-overpy.git",
    "timestamp": "2023-05-29T15:50:10.954173Z",
    "clone_success": true,
    "number of actions": 3,
    "number_of_test_actions": 1,
    "actions_successful": true,
    "actions_stdout": "[Tests/Python Linux on ubuntu-latest] \ud83d\ude80  Start image=crawlergpt:latest\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/DinoTools-python-overpy] user=0 workdir=\n[Tests/Python Linux on ubuntu-latest]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v2\n[Tests/Python Linux on ubuntu-latest]   \u2601  git clone 'https://github.com/actions/cache' # ref=v2\n[Tests/Python Linux on ubuntu-latest] \ud83e\uddea  Matrix: map[name:Linux os:ubuntu-latest python:3.9 tox:py39]\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Main actions/checkout@v2\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Main actions/checkout@v2\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Main actions/setup-python@v2\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v2/ dst=/var/run/act/actions/actions-setup-python@v2/\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v2/] user=0 workdir=\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/setup/index.js] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::Semantic version spec of 3.9 is 3.9\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::isExplicit: \n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::explicit? false\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::explicit? true\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::explicit? true\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::explicit? true\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::explicit? true\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::explicit? true\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::explicit? true\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::evaluating 6 versions\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::matched: 3.9.6\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.9.6/x64\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::Found tool in cache Python 3.9.6 x64\n[Tests/Python Linux on ubuntu-latest]   | Successfully setup CPython (3.9.6)\n[Tests/Python Linux on ubuntu-latest]   \u2753 add-matcher /run/act/actions/actions-setup-python@v2/.github/python.json\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Main actions/setup-python@v2\n[Tests/Python Linux on ubuntu-latest]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.9.6/x64\n[Tests/Python Linux on ubuntu-latest]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.9.6/x64/lib\n[Tests/Python Linux on ubuntu-latest]   \u2699  ::set-output:: python-version=3.9.6\n[Tests/Python Linux on ubuntu-latest]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.9.6/x64\n[Tests/Python Linux on ubuntu-latest]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.9.6/x64/bin\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Main update pip\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   | Python 3.9.6 (default, Jun 28 2021, 19:59:42) \n[Tests/Python Linux on ubuntu-latest]   | [GCC 9.3.0]\n[Tests/Python Linux on ubuntu-latest]   | sys.path = [\n[Tests/Python Linux on ubuntu-latest]   |     '/tmp/de65f406-fe28-11ed-a890-af2cc187fc11/DinoTools-python-overpy',\n[Tests/Python Linux on ubuntu-latest]   |     '/opt/hostedtoolcache/Python/3.9.6/x64/lib/python39.zip',\n[Tests/Python Linux on ubuntu-latest]   |     '/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9',\n[Tests/Python Linux on ubuntu-latest]   |     '/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/lib-dynload',\n[Tests/Python Linux on ubuntu-latest]   |     '/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages',\n[Tests/Python Linux on ubuntu-latest]   | ]\n[Tests/Python Linux on ubuntu-latest]   | USER_BASE: '/home/runneradmin/.local' (doesn't exist)\n[Tests/Python Linux on ubuntu-latest]   | USER_SITE: '/home/runneradmin/.local/lib/python3.9/site-packages' (doesn't exist)\n[Tests/Python Linux on ubuntu-latest]   | ENABLE_USER_SITE: True\n[Tests/Python Linux on ubuntu-latest]   | Collecting wheel\n[Tests/Python Linux on ubuntu-latest]   |   Downloading wheel-0.40.0-py3-none-any.whl (64 kB)\n[Tests/Python Linux on ubuntu-latest]   | Installing collected packages: wheel\n[Tests/Python Linux on ubuntu-latest]   | Successfully installed wheel-0.40.0\n[Tests/Python Linux on ubuntu-latest]   | WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.\n[Tests/Python Linux on ubuntu-latest]   | You should consider upgrading via the '/opt/hostedtoolcache/Python/3.9.6/x64/bin/python -m pip install --upgrade pip' command.\n[Tests/Python Linux on ubuntu-latest]   | Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages (56.0.0)\n[Tests/Python Linux on ubuntu-latest]   | Collecting setuptools\n[Tests/Python Linux on ubuntu-latest]   |   Downloading setuptools-67.8.0-py3-none-any.whl (1.1 MB)\n[Tests/Python Linux on ubuntu-latest]   | Installing collected packages: setuptools\n[Tests/Python Linux on ubuntu-latest]   |   Attempting uninstall: setuptools\n[Tests/Python Linux on ubuntu-latest]   |     Found existing installation: setuptools 56.0.0\n[Tests/Python Linux on ubuntu-latest]   |     Uninstalling setuptools-56.0.0:\n[Tests/Python Linux on ubuntu-latest]   |       Successfully uninstalled setuptools-56.0.0\n[Tests/Python Linux on ubuntu-latest]   | Successfully installed setuptools-67.8.0\n[Tests/Python Linux on ubuntu-latest]   | WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.\n[Tests/Python Linux on ubuntu-latest]   | You should consider upgrading via the '/opt/hostedtoolcache/Python/3.9.6/x64/bin/python -m pip install --upgrade pip' command.\n[Tests/Python Linux on ubuntu-latest]   | Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages (21.2.4)\n[Tests/Python Linux on ubuntu-latest]   | Collecting pip\n[Tests/Python Linux on ubuntu-latest]   |   Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)\n[Tests/Python Linux on ubuntu-latest]   | Installing collected packages: pip\n[Tests/Python Linux on ubuntu-latest]   |   Attempting uninstall: pip\n[Tests/Python Linux on ubuntu-latest]   |     Found existing installation: pip 21.2.4\n[Tests/Python Linux on ubuntu-latest]   |     Uninstalling pip-21.2.4:\n[Tests/Python Linux on ubuntu-latest]   |       Successfully uninstalled pip-21.2.4\n[Tests/Python Linux on ubuntu-latest]   | Successfully installed pip-23.1.2\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Main update pip\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Main get pip cache dir\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/pip-cache] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   \u2699  ::set-output:: dir=/home/runneradmin/.cache/pip\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Main get pip cache dir\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Main cache pip\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-cache@v2/ dst=/var/run/act/actions/actions-cache@v2/\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-cache@v2/] user=0 workdir=\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-cache@v2/dist/restore/index.js] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::Resolved Keys:\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::[\"pip|Linux|3.9|500fbf1bd45591785ffa40ac21e6779b1090a4786220f039aa9cce4b565cf0a8|\"]\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::Checking zstd --version\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::*** zstd command line interface 64-bits v1.5.0, by Yann Collet ***\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.\n[Tests/Python Linux on ubuntu-latest]   | [warning]getCacheEntry failed: Cache Service Url not found, unable to restore cache.\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Main cache pip\n[Tests/Python Linux on ubuntu-latest]   \u2699  ::set-output:: cache-hit=false\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Main pip install tox\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   | Collecting tox\n[Tests/Python Linux on ubuntu-latest]   |   Downloading tox-4.5.2-py3-none-any.whl (148 kB)\n[Tests/Python Linux on ubuntu-latest]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 149.0/149.0 kB 2.7 MB/s eta 0:00:00\n[Tests/Python Linux on ubuntu-latest]   | Collecting cachetools>=5.3 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading cachetools-5.3.1-py3-none-any.whl (9.3 kB)\n[Tests/Python Linux on ubuntu-latest]   | Collecting chardet>=5.1 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading chardet-5.1.0-py3-none-any.whl (199 kB)\n[Tests/Python Linux on ubuntu-latest]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 199.1/199.1 kB 18.8 MB/s eta 0:00:00\n[Tests/Python Linux on ubuntu-latest]   | Collecting colorama>=0.4.6 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)\n[Tests/Python Linux on ubuntu-latest]   | Collecting filelock>=3.12 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading filelock-3.12.0-py3-none-any.whl (10 kB)\n[Tests/Python Linux on ubuntu-latest]   | Collecting packaging>=23.1 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading packaging-23.1-py3-none-any.whl (48 kB)\n[Tests/Python Linux on ubuntu-latest]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 48.9/48.9 kB 2.0 MB/s eta 0:00:00\n[Tests/Python Linux on ubuntu-latest]   | Collecting platformdirs>=3.5.1 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading platformdirs-3.5.1-py3-none-any.whl (15 kB)\n[Tests/Python Linux on ubuntu-latest]   | Collecting pluggy>=1 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)\n[Tests/Python Linux on ubuntu-latest]   | Collecting pyproject-api>=1.5.1 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading pyproject_api-1.5.1-py3-none-any.whl (12 kB)\n[Tests/Python Linux on ubuntu-latest]   | Collecting tomli>=2.0.1 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)\n[Tests/Python Linux on ubuntu-latest]   | Collecting virtualenv>=20.23 (from tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading virtualenv-20.23.0-py3-none-any.whl (3.3 MB)\n[Tests/Python Linux on ubuntu-latest]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 3.3/3.3 MB 39.6 MB/s eta 0:00:00\n[Tests/Python Linux on ubuntu-latest]   | Collecting distlib<1,>=0.3.6 (from virtualenv>=20.23->tox)\n[Tests/Python Linux on ubuntu-latest]   |   Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)\n[Tests/Python Linux on ubuntu-latest]   |      \u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501 468.5/468.5 kB 8.0 MB/s eta 0:00:00\n[Tests/Python Linux on ubuntu-latest]   | Installing collected packages: distlib, tomli, pluggy, platformdirs, packaging, filelock, colorama, chardet, cachetools, virtualenv, pyproject-api, tox\n[Tests/Python Linux on ubuntu-latest]   | Successfully installed cachetools-5.3.1 chardet-5.1.0 colorama-0.4.6 distlib-0.3.6 filelock-3.12.0 packaging-23.1 platformdirs-3.5.1 pluggy-1.0.0 pyproject-api-1.5.1 tomli-2.0.1 tox-4.5.2 virtualenv-20.23.0\n[Tests/Python Linux on ubuntu-latest]   | \n[Tests/Python Linux on ubuntu-latest]   | [notice] A new release of pip is available: 21.1.3 -> 23.1.2\n[Tests/Python Linux on ubuntu-latest]   | [notice] To update, run: pip install --upgrade pip\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Main pip install tox\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Main Run tox targets for 3.9\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/6] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   | py39: install_deps> python -I -m pip install pytest pytest-cov\n[Tests/Python Linux on ubuntu-latest]   | .pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel\n[Tests/Python Linux on ubuntu-latest]   | .pkg: _optional_hooks> python /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\n[Tests/Python Linux on ubuntu-latest]   | .pkg: get_requires_for_build_sdist> python /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\n[Tests/Python Linux on ubuntu-latest]   | .pkg: install_requires_for_build_sdist> python -I -m pip install pytest-runner\n[Tests/Python Linux on ubuntu-latest]   | .pkg: freeze> python -m pip freeze --all\n[Tests/Python Linux on ubuntu-latest]   | .pkg: pip==23.1.2,pytest-runner==6.0.0,setuptools==67.7.2,wheel==0.40.0\n[Tests/Python Linux on ubuntu-latest]   | .pkg: prepare_metadata_for_build_wheel> python /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\n[Tests/Python Linux on ubuntu-latest]   | .pkg: build_sdist> python /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\n[Tests/Python Linux on ubuntu-latest]   | py39: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/DinoTools-python-overpy/.tox/.tmp/package/1/overpy-0.6.tar.gz\n[Tests/Python Linux on ubuntu-latest]   | py39: freeze> python -m pip freeze --all\n[Tests/Python Linux on ubuntu-latest]   | py39: coverage==7.2.6,exceptiongroup==1.1.1,iniconfig==2.0.0,overpy @ file:///tmp/de65f406-fe28-11ed-a890-af2cc187fc11/DinoTools-python-overpy/.tox/.tmp/package/1/overpy-0.6.tar.gz#sha256=1eb03a3e0deb547872819d3d11a5fea921939db0d57371c19fba918f7dbd11b5,packaging==23.1,pip==23.1.2,pluggy==1.0.0,pytest==7.3.1,pytest-cov==4.1.0,setuptools==67.7.2,tomli==2.0.1,wheel==0.40.0\n[Tests/Python Linux on ubuntu-latest]   | py39: commands[0]> pytest --cov overpy --cov-report=term-missing -v tests/\n[Tests/Python Linux on ubuntu-latest]   | ============================= test session starts ==============================\n[Tests/Python Linux on ubuntu-latest]   | platform linux -- Python 3.9.6, pytest-7.3.1, pluggy-1.0.0 -- /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/DinoTools-python-overpy/.tox/py39/bin/python\n[Tests/Python Linux on ubuntu-latest]   | cachedir: .tox/py39/.pytest_cache\n[Tests/Python Linux on ubuntu-latest]   | rootdir: /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/DinoTools-python-overpy\n[Tests/Python Linux on ubuntu-latest]   | configfile: setup.cfg\n[Tests/Python Linux on ubuntu-latest]   | plugins: cov-4.1.0\n[Tests/Python Linux on ubuntu-latest]   | collecting ... collected 63 items\n[Tests/Python Linux on ubuntu-latest]   | \n[Tests/Python Linux on ubuntu-latest]   | tests/test_exception.py::TestExceptions::test_element_data_wrong_type PASSED [  1%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_exception.py::TestExceptions::test_overpass_bad_request PASSED [  3%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_exception.py::TestExceptions::test_overpass_unknown_content_type PASSED [  4%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_exception.py::TestExceptions::test_overpass_unknown_http_status_code PASSED [  6%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_exception.py::TestExceptions::test_overpass_error PASSED      [  7%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestAreas::test_area01 PASSED                        [  9%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestNodes::test_node01 PASSED                        [ 11%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestRelation::test_relation01 PASSED                 [ 12%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestRelation::test_relation02 PASSED                 [ 14%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestRelation::test_relation03 PASSED                 [ 15%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestRelation::test_relation04 PASSED                 [ 17%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestWay::test_way01 PASSED                           [ 19%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestWay::test_way02 PASSED                           [ 20%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestWay::test_way03 PASSED                           [ 22%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestWay::test_way04 PASSED                           [ 23%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestDataError::test_element_wrong_type PASSED        [ 25%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestRemark::test_remark_runtime_error PASSED         [ 26%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestRemark::test_remark_runtime_remark PASSED        [ 28%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_json.py::TestRemark::test_remark_unknown PASSED               [ 30%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_chunk_size PASSED                 [ 31%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_overpass_syntax_error PASSED      [ 33%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_overpass_syntax_error_encoding_error PASSED [ 34%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_overpass_too_many_requests PASSED [ 36%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_overpass_gateway_timeout PASSED   [ 38%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_overpass_unknown_status_code PASSED [ 39%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_response_json PASSED              [ 41%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_response_unknown PASSED           [ 42%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_response_xml PASSED               [ 44%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_request.py::TestQuery::test_retry PASSED                      [ 46%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestResult::test_expand_error PASSED               [ 47%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestResult::test_expand_01 PASSED                  [ 49%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestArea::test_missing_unresolvable PASSED         [ 50%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestArea::test_missing_resolvable PASSED           [ 52%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestNode::test_missing_unresolvable PASSED         [ 53%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestNode::test_missing_resolvable PASSED           [ 55%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestPickle::test_way02 PASSED                      [ 57%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestRelation::test_missing_unresolvable PASSED     [ 58%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestRelation::test_missing_resolvable PASSED       [ 60%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestWay::test_missing_unresolvable PASSED          [ 61%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result.py::TestWay::test_missing_resolvable PASSED            [ 63%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result_way.py::TestNodes::test_missing_unresolvable PASSED    [ 65%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result_way.py::TestNodes::test_missing_partly_unresolvable PASSED [ 66%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_result_way.py::TestNodes::test_missing_resolvable PASSED      [ 68%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestAreas::test_node01 PASSED                         [ 69%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestNodes::test_node01 PASSED                         [ 71%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestRelation::test_relation01 PASSED                  [ 73%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestRelation::test_relation02 PASSED                  [ 74%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestRelation::test_relation03 PASSED                  [ 76%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestRelation::test_relation04 PASSED                  [ 77%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestWay::test_way01 PASSED                            [ 79%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestWay::test_way02 PASSED                            [ 80%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestWay::test_way03 PASSED                            [ 82%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestWay::test_way04 PASSED                            [ 84%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestDataError::test_element_wrong_type PASSED         [ 85%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestDataError::test_node_missing_data PASSED          [ 87%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestDataError::test_relation_missing_data PASSED      [ 88%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestDataError::test_way_missing_data PASSED           [ 90%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestParser::test_exception PASSED                     [ 92%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestParser::test_xml_element PASSED                   [ 93%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestParser::test_xml_autodetect_parser PASSED         [ 95%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestRemark::test_remark_runtime_error PASSED          [ 96%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestRemark::test_remark_runtime_remark PASSED         [ 98%]\n[Tests/Python Linux on ubuntu-latest]   | tests/test_xml.py::TestRemark::test_remark_unknown PASSED                [100%]\n[Tests/Python Linux on ubuntu-latest]   | \n[Tests/Python Linux on ubuntu-latest]   | ----------- coverage: platform linux, python 3.9.6-final-0 -----------\n[Tests/Python Linux on ubuntu-latest]   | Name                  Stmts   Miss  Cover   Missing\n[Tests/Python Linux on ubuntu-latest]   | ---------------------------------------------------\n[Tests/Python Linux on ubuntu-latest]   | overpy/__about__.py       9      0   100%\n[Tests/Python Linux on ubuntu-latest]   | overpy/__init__.py      745     32    96%   79, 413, 421, 665, 675, 696, 709, 723, 740, 751, 765, 796, 913, 1100, 1270, 1325, 1355, 1365, 1374, 1381, 1384, 1391, 1394, 1427-1428, 1441-1442, 1467-1468, 1566-1567, 1620\n[Tests/Python Linux on ubuntu-latest]   | overpy/exception.py      63      1    98%   49\n[Tests/Python Linux on ubuntu-latest]   | overpy/helper.py         15     15     0%   1-72\n[Tests/Python Linux on ubuntu-latest]   | ---------------------------------------------------\n[Tests/Python Linux on ubuntu-latest]   | TOTAL                   832     48    94%\n[Tests/Python Linux on ubuntu-latest]   | \n[Tests/Python Linux on ubuntu-latest]   | \n[Tests/Python Linux on ubuntu-latest]   | ============================= 63 passed in 15.17s ==============================\n[Tests/Python Linux on ubuntu-latest]   | .pkg: _exit> python /opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\n[Tests/Python Linux on ubuntu-latest]   |   py39: OK (32.80=setup[16.91]+cmd[15.89] seconds)\n[Tests/Python Linux on ubuntu-latest]   |   congratulations :) (33.34 seconds)\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Main Run tox targets for 3.9\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Post cache pip\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-cache@v2/dist/save/index.js] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::Checking zstd --version\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::*** zstd command line interface 64-bits v1.5.0, by Yann Collet ***\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::Reserving Cache\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::reserveCache - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udcac  ::debug::reserveCache - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.\n[Tests/Python Linux on ubuntu-latest]   | [warning]reserveCache failed: Cache Service Url not found, unable to restore cache.\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Post cache pip\n[Tests/Python Linux on ubuntu-latest] \u2b50 Run Post actions/setup-python@v2\n[Tests/Python Linux on ubuntu-latest]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v2/dist/cache-save/index.js] user= workdir=\n[Tests/Python Linux on ubuntu-latest]   \u2705  Success - Post actions/setup-python@v2\n[Tests/Python Linux on ubuntu-latest] \ud83c\udfc1  Job succeeded\n",
    "actions_stderr": ""
}