{
    "repository": "pallets/flask",
    "clone_url": "https://github.com/pallets/flask.git",
    "timestamp": "2023-05-29T14:01:58.429380Z",
    "clone_success": true,
    "number of actions": 3,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Tests/Linux] \ud83d\ude80  Start image=crawlergpt:latest\n[Tests/Linux]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Tests/Linux]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Tests/Linux]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Tests/Linux]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/pallets-flask] user=0 workdir=\n[Tests/Linux]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=57ded4d7d5e986d7296eab16560982c6dd7c923b\n[Tests/Linux]   \u2601  git clone 'https://github.com/actions/cache' # ref=88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8\n[Tests/Linux] \ud83e\uddea  Matrix: map[name:Linux os:ubuntu-latest python:3.11 tox:py311]\n[Tests/Linux] \u2b50 Run Main actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab\n[Tests/Linux]   \u2705  Success - Main actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab\n[Tests/Linux] \u2b50 Run Main actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b\n[Tests/Linux]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b/ dst=/var/run/act/actions/actions-setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b/\n[Tests/Linux]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b/] user=0 workdir=\n[Tests/Linux]   | OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown\r\n[Tests/Linux]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b/dist/setup/index.js] user= workdir=\n[Tests/Linux]   \u274c  Failure - Main actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b\n[Tests/Linux] Error response from daemon: Could not find the file /var/run/act/workflow/pathcmd.txt in container df6f52085d9a6f9957930ad95e4f192c2b8dae3913c0fb1ac0b3480c56ea77c5\n[Tests/Linux] failed to remove container: Error response from daemon: No such container: df6f52085d9a6f9957930ad95e4f192c2b8dae3913c0fb1ac0b3480c56ea77c5\n[Tests/Linux] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Error occurred running finally: Error occurred running finally: Error response from daemon: remove act-Tests-Linux-994b5a09e8eb967eaf54f6dfb72bc466ac879d12644e9e2bd4704a15e7b55d18-env: volume is in use - [cf39883a66d5bf61c293027190a71c4ee458a884916f187048c7a7120ba86ef1] (original error: <nil>) (original error: <nil>)\n"
}