{
    "repository": "persian-tools/py-persian-tools",
    "clone_url": "https://github.com/persian-tools/py-persian-tools.git",
    "timestamp": "2023-05-29T16:21:15.132988Z",
    "clone_success": true,
    "number of actions": 1,
    "number_of_test_actions": 1,
    "actions_successful": false,
    "actions_stdout": "[Test/test] \ud83d\ude80  Start image=crawlergpt:latest\n[Test/test]   \ud83d\udc33  docker pull image=crawlergpt:latest platform= username= forcePull=false\n[Test/test]   \ud83d\udc33  docker create image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Test/test]   \ud83d\udc33  docker run image=crawlergpt:latest platform= entrypoint=[\"tail\" \"-f\" \"/dev/null\"] cmd=[]\n[Test/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/persian-tools-py-persian-tools] user=0 workdir=\n[Test/test]   \u2601  git clone 'https://github.com/actions/setup-python' # ref=v4\n[Test/test]   \u2601  git clone 'https://github.com/codecov/codecov-action' # ref=v3\n[Test/test] \ud83e\uddea  Matrix: map[python-version:3.6]\n[Test/test] \u2b50 Run Main actions/checkout@v3\n[Test/test]   \u2705  Success - Main actions/checkout@v3\n[Test/test] \u2b50 Run Main Set up Python 3.6\n[Test/test]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/actions-setup-python@v4/ dst=/var/run/act/actions/actions-setup-python@v4/\n[Test/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/actions-setup-python@v4/] user=0 workdir=\n[Test/test]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/actions-setup-python@v4/dist/setup/index.js] user= workdir=\n[Test/test]   \ud83d\udcac  ::debug::Python is expected to be installed into /opt/hostedtoolcache\n[Test/test]   \u2753  ::group::Installed versions\n[Test/test]   \ud83d\udcac  ::debug::Semantic version spec of 3.6 is 3.6\n[Test/test]   \ud83d\udcac  ::debug::isExplicit: \n[Test/test]   \ud83d\udcac  ::debug::explicit? false\n[Test/test]   \ud83d\udcac  ::debug::isExplicit: 2.7.18\n[Test/test]   \ud83d\udcac  ::debug::explicit? true\n[Test/test]   \ud83d\udcac  ::debug::isExplicit: 3.5.10\n[Test/test]   \ud83d\udcac  ::debug::explicit? true\n[Test/test]   \ud83d\udcac  ::debug::isExplicit: 3.6.14\n[Test/test]   \ud83d\udcac  ::debug::explicit? true\n[Test/test]   \ud83d\udcac  ::debug::isExplicit: 3.7.11\n[Test/test]   \ud83d\udcac  ::debug::explicit? true\n[Test/test]   \ud83d\udcac  ::debug::isExplicit: 3.8.11\n[Test/test]   \ud83d\udcac  ::debug::explicit? true\n[Test/test]   \ud83d\udcac  ::debug::isExplicit: 3.9.6\n[Test/test]   \ud83d\udcac  ::debug::explicit? true\n[Test/test]   \ud83d\udcac  ::debug::evaluating 6 versions\n[Test/test]   \ud83d\udcac  ::debug::matched: 3.6.14\n[Test/test]   \ud83d\udcac  ::debug::checking cache: /opt/hostedtoolcache/Python/3.6.14/x64\n[Test/test]   \ud83d\udcac  ::debug::Found tool in cache Python 3.6.14 x64\n[Test/test]   | Successfully set up CPython (3.6.14)\n[Test/test]   \u2753  ::endgroup::\n[Test/test]   \u2753 add-matcher /run/act/actions/actions-setup-python@v4/.github/python.json\n[Test/test]   \u2705  Success - Main Set up Python 3.6\n[Test/test]   \u2699  ::set-env:: Python3_ROOT_DIR=/opt/hostedtoolcache/Python/3.6.14/x64\n[Test/test]   \u2699  ::set-env:: LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.6.14/x64/lib\n[Test/test]   \u2699  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.6.14/x64\n[Test/test]   \u2699  ::set-env:: PKG_CONFIG_PATH=/opt/hostedtoolcache/Python/3.6.14/x64/lib/pkgconfig\n[Test/test]   \u2699  ::set-env:: Python_ROOT_DIR=/opt/hostedtoolcache/Python/3.6.14/x64\n[Test/test]   \u2699  ::set-env:: Python2_ROOT_DIR=/opt/hostedtoolcache/Python/3.6.14/x64\n[Test/test]   \u2699  ::set-output:: python-version=3.6.14\n[Test/test]   \u2699  ::set-output:: python-path=/opt/hostedtoolcache/Python/3.6.14/x64/bin/python\n[Test/test]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.6.14/x64\n[Test/test]   \u2699  ::add-path:: /opt/hostedtoolcache/Python/3.6.14/x64/bin\n[Test/test] \u2b50 Run Main Test\n[Test/test]   \ud83d\udc33  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=\n[Test/test]   | Collecting pytest\n[Test/test]   |   Downloading pytest-7.0.1-py3-none-any.whl (296 kB)\n[Test/test]   | Collecting pytest-cov\n[Test/test]   |   Downloading pytest_cov-4.0.0-py3-none-any.whl (21 kB)\n[Test/test]   | Collecting attrs>=19.2.0\n[Test/test]   |   Downloading attrs-22.2.0-py3-none-any.whl (60 kB)\n[Test/test]   | Collecting iniconfig\n[Test/test]   |   Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)\n[Test/test]   | Collecting py>=1.8.2\n[Test/test]   |   Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)\n[Test/test]   | Collecting pluggy<2.0,>=0.12\n[Test/test]   |   Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)\n[Test/test]   | Collecting packaging\n[Test/test]   |   Downloading packaging-21.3-py3-none-any.whl (40 kB)\n[Test/test]   | Collecting importlib-metadata>=0.12\n[Test/test]   |   Downloading importlib_metadata-4.8.3-py3-none-any.whl (17 kB)\n[Test/test]   | Collecting tomli>=1.0.0\n[Test/test]   |   Downloading tomli-1.2.3-py3-none-any.whl (12 kB)\n[Test/test]   | Collecting coverage[toml]>=5.2.1\n[Test/test]   |   Downloading coverage-6.2-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (212 kB)\n[Test/test]   | Collecting zipp>=0.5\n[Test/test]   |   Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)\n[Test/test]   | Collecting typing-extensions>=3.6.4\n[Test/test]   |   Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)\n[Test/test]   | Collecting pyparsing!=3.0.5,>=2.0.2\n[Test/test]   |   Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)\n[Test/test]   | Installing collected packages: zipp, typing-extensions, pyparsing, importlib-metadata, tomli, py, pluggy, packaging, iniconfig, coverage, attrs, pytest, pytest-cov\n[Test/test]   | Successfully installed attrs-22.2.0 coverage-6.2 importlib-metadata-4.8.3 iniconfig-1.1.1 packaging-21.3 pluggy-1.0.0 py-1.11.0 pyparsing-3.0.9 pytest-7.0.1 pytest-cov-4.0.0 tomli-1.2.3 typing-extensions-4.1.1 zipp-3.6.0\n[Test/test]   | WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.\n[Test/test]   | You should consider upgrading via the '/opt/hostedtoolcache/Python/3.6.14/x64/bin/python -m pip install --upgrade pip' command.\n[Test/test]   | ============================= test session starts ==============================\n[Test/test]   | platform linux -- Python 3.6.14, pytest-7.0.1, pluggy-1.0.0\n[Test/test]   | rootdir: /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/persian-tools-py-persian-tools\n[Test/test]   | plugins: cov-4.0.0\n[Test/test]   | collected 43 items\n[Test/test]   | \n[Test/test]   | tests/test_bank_card_number.py .......                                   [ 16%]\n[Test/test]   | tests/test_bank_sheba.py ..                                              [ 20%]\n[Test/test]   | tests/test_bill.py ........                                              [ 39%]\n[Test/test]   | tests/test_digis.py .........                                            [ 60%]\n[Test/test]   | tests/test_legal_id.py ..                                                [ 65%]\n[Test/test]   | tests/test_national_id.py ...                                            [ 72%]\n[Test/test]   | tests/test_ordinal_suffix.py ..                                          [ 76%]\n[Test/test]   | tests/test_phone_number.py ...                                           [ 83%]\n[Test/test]   | tests/test_plate.py .....                                                [ 95%]\n[Test/test]   | tests/test_separator.py ..                                               [100%]\n[Test/test]   | \n[Test/test]   | =============================== warnings summary ===============================\n[Test/test]   | persian_tools/phone_number/__init__.py:8\n[Test/test]   |   /tmp/de65f406-fe28-11ed-a890-af2cc187fc11/persian-tools-py-persian-tools/persian_tools/phone_number/__init__.py:8: DeprecationWarning: invalid escape sequence \\+\n[Test/test]   |     MOBILE_SUFFIX_REGEX = '^(?:\\+98|98|0098|0)'\n[Test/test]   | \n[Test/test]   | -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n[Test/test]   | \n[Test/test]   | ---------- coverage: platform linux, python 3.6.14-final-0 -----------\n[Test/test]   | Coverage XML written to file coverage.xml\n[Test/test]   | \n[Test/test]   | ======================== 43 passed, 1 warning in 1.15s =========================\n[Test/test]   \u2705  Success - Main Test\n[Test/test] \u2b50 Run Main Upload coverage\n[Test/test]   \ud83d\udc33  docker cp src=/home/andre-silva/.cache/act/codecov-codecov-action@v3/ dst=/var/run/act/actions/codecov-codecov-action@v3/\n[Test/test]   \ud83d\udc33  docker exec cmd=[chown -R 1012:1000 /var/run/act/actions/codecov-codecov-action@v3/] user=0 workdir=\n[Test/test]   \ud83d\udc33  docker exec cmd=[node /var/run/act/actions/codecov-codecov-action@v3/dist/index.js] user= workdir=\n[Test/test]   | Error: Cannot find module 'node:http'\n[Test/test]   | Require stack:\n[Test/test]   | - /run/act/actions/codecov-codecov-action@v3/dist/index.js\n[Test/test]   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)\n[Test/test]   |     at Function.Module._load (internal/modules/cjs/loader.js:745:27)\n[Test/test]   |     at Module.require (internal/modules/cjs/loader.js:961:19)\n[Test/test]   |     at require (internal/modules/cjs/helpers.js:92:18)\n[Test/test]   |     at /run/act/actions/codecov-codecov-action@v3/webpack:/codecov-action/external node-commonjs \"node:http\":1:1\n[Test/test]   |     at /run/act/actions/codecov-codecov-action@v3/dist/index.js:24630:3\n[Test/test]   |     at Object.<anonymous> (/run/act/actions/codecov-codecov-action@v3/dist/index.js:24633:12)\n[Test/test]   |     at Module._compile (internal/modules/cjs/loader.js:1072:14)\n[Test/test]   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n[Test/test]   |     at Module.load (internal/modules/cjs/loader.js:937:32)\n[Test/test]   \u274c  Failure - Main Upload coverage\n[Test/test] exitcode '1': failure\n[Test/test] failed to remove container: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.41/containers/e987d18e6b305f52693ef837ab0f09ee4238040d1dd5b06879652eaed5303c28?force=1&v=1\": context deadline exceeded\n[Test/test] \ud83c\udfc1  Job failed\n",
    "actions_stderr": "Error: Error occurred running finally: Error occurred running finally: context deadline exceeded (original error: <nil>) (original error: <nil>)\n"
}